export const initialExamCenters = [
  {
    id: 1,
    title: "حوزه تهران ۱",
    capacity: 500,
    contractDate: "1403/01/15",
    province: "تهران",
    city: "تهران",
    address: "تهران، خیابان انقلاب، کوچه بهار",
    phone: "12345678-021",
    status: "فعال",
    category: "حوزه‌های من",
    gender: "زن",
    firstName: "زهرا",
    lastName: "احمدی",
    contractAmount: "50,000,000",
  },
  {
    id: 2,
    title: "حوزه اصفهان ۱",
    capacity: 300,
    contractDate: "1403/02/10",
    province: "اصفهان",
    city: "اصفهان",
    address: "اصفهان، چهارباغ بالا، کوچه گلستان",
    phone: "87654321-031",
    status: "غیرفعال",
    category: "حوزه‌های من",
    gender: "مرد",
    firstName: "علی",
    lastName: "کریمی",
    contractAmount: "30,000,000",
  },
  {
    id: 3,
    title: "حوزه شیراز ۱",
    capacity: 400,
    contractDate: "1403/03/20",
    province: "فارس",
    city: "شیراز",
    address: "شیراز، خیابان زند، کوچه ۱۰",
    phone: "23456789-071",
    status: "فعال",
    category: "حوزه‌های من",
    gender: "زن/مرد",
    firstName: "مریم",
    lastName: "نظری",
    contractAmount: "40,000,000",
  },
  {
    id: 4,
    title: "حوزه مشهد ۱",
    capacity: 600,
    contractDate: "1403/04/05",
    province: "خراسان رضوی",
    city: "مشهد",
    address: "مشهد، بلوار وکیل‌آباد، خیابان ۱۵",
    phone: "34567890-051",
    status: "فعال",
    category: "حوزه‌های من",
    gender: "زن",
    firstName: "رضا",
    lastName: "کاظمی",
    contractAmount: "60,000,000",
  },
  {
    id: 5,
    title: "حوزه تبریز ۱",
    capacity: 350,
    contractDate: "1403/05/12",
    province: "آذربایجان شرقی",
    city: "تبریز",
    address: "تبریز، خیابان امام، کوچه ۸",
    phone: "45678901-041",
    status: "غیرفعال",
    category: "حوزه‌های من",
    gender: "مرد",
    firstName: "سعید",
    lastName: "اکبری",
    contractAmount: "35,000,000",
  },
  {
    id: 6,
    title: "حوزه کرج ۱",
    capacity: 450,
    contractDate: "1403/06/01",
    province: "البرز",
    city: "کرج",
    address: "کرج، بلوار طالقانی، خیابان گل‌ها",
    phone: "56789012-026",
    status: "فعال",
    category: "حوزه‌های من",
    gender: "زن/مرد",
    firstName: "الهام",
    lastName: "صادقی",
    contractAmount: "45,000,000",
  },
  {
    id: 7,
    title: "حوزه قم ۱",
    capacity: 200,
    contractDate: "1403/07/15",
    province: "قم",
    city: "قم",
    address: "قم، خیابان صفاییه، کوچه ۱۲",
    phone: "67890123-025",
    status: "فعال",
    category: "حوزه‌های من",
    gender: "زن",
    firstName: "زینب",
    lastName: "ملکی",
    contractAmount: "20,000,000",
  },
  {
    id: 8,
    title: "حوزه اهواز ۱",
    capacity: 500,
    contractDate: "1403/08/10",
    province: "خوزستان",
    city: "اهواز",
    address: "اهواز، کیانپارس، خیابان ۵",
    phone: "78901234-061",
    status: "غیرفعال",
    category: "حوزه‌های من",
    gender: "مرد",
    firstName: "حسین",
    lastName: "یوسفی",
    contractAmount: "50,000,000",
  },
  {
    id: 9,
    title: "حوزه رشت ۱",
    capacity: 300,
    contractDate: "1403/09/05",
    province: "گیلان",
    city: "رشت",
    address: "رشت، گلسار، خیابان ۲۰",
    phone: "89012345-013",
    status: "فعال",
    category: "حوزه‌های من",
    gender: "زن/مرد",
    firstName: "نسیم",
    lastName: "افشار",
    contractAmount: "30,000,000",
  },
  {
    id: 10,
    title: "حوزه یزد ۱",
    capacity: 250,
    contractDate: "1403/10/20",
    province: "یزد",
    city: "یزد",
    address: "یزد، بلوار دانشگاه، کوچه ۳",
    phone: "90123456-035",
    status: "غیرفعال",
    category: "حوزه‌های من",
    gender: "زن",
    firstName: "مونا",
    lastName: "زارعی",
    contractAmount: "25,000,000",
  },
];
