export const sampleIssuedPermits = [
  {
    id: 1,
    permitNumber: "PM-001",
    status: "صادر شده",
    organization: "وزارت آموزش و پرورش",
    subOrganization: "اداره کل تهران",
    employmentType: "رسمی",
    scoreRatio: "70%",
    registrationDate: "1403/01/20",
    hiringCapacity: 130,
    capacityMultiplier: "3 برابر",
    confirmationDate: "1403/02/10",
  },
  {
    id: 2,
    permitNumber: "PM-002",
    status: "صادر شده",
    organization: "وزارت بهداشت",
    subOrganization: "دانشگاه علوم پزشکی",
    employmentType: "پیمانی",
    scoreRatio: "60%",
    registrationDate: "1403/02/15",
    hiringCapacity: 90,
    capacityMultiplier: "2 برابر",
    confirmationDate: "1403/03/10",
  },
  {
    id: 3,
    permitNumber: "PM-003",
    status: "منقضی شده",
    organization: "وزارت نیرو",
    subOrganization: "شرکت برق منطقه‌ای",
    employmentType: "قراردادی",
    scoreRatio: "50%",
    registrationDate: "1403/03/10",
    hiringCapacity: 60,
    capacityMultiplier: "4 برابر",
    confirmationDate: "1403/04/10",
  },
  {
    id: 4,
    permitNumber: "PM-004",
    status: "صادر شده",
    organization: "وزارت آموزش و پرورش",
    subOrganization: "اداره کل تهران",
    employmentType: "رسمی",
    scoreRatio: "70%",
    registrationDate: "1403/04/20",
    hiringCapacity: 160,
    capacityMultiplier: "3 برابر",
    confirmationDate: "1403/05/10",
  },
  {
    id: 5,
    permitNumber: "PM-005",
    status: "باطل شده",
    organization: "وزارت بهداشت",
    subOrganization: "دانشگاه علوم پزشکی",
    employmentType: "پیمانی",
    scoreRatio: "60%",
    registrationDate: "1403/05/15",
    hiringCapacity: 100,
    capacityMultiplier: "2 برابر",
    confirmationDate: "1403/06/10",
  },
];
