export const initialExamResults = [
  {
    id: 1,
    examName: "دوازدهمین امتحان مشترک فراگیر دستگاه‌های اجرایی کشور",
    organizer: "سازمان سنجش و آموزش کشور",
    resultFile: "/files/exam7-results.pdf",
    detailsFile: "/files/exam7-details.pdf",
    participants: 950,
    organization: "سازمان برنامه و بودجه کشور",
    status: "در حال بررسی",
    resultDate: "1404/2/20",
    examDate: "1403/12/27",
  },
  {
    id: 13,
    examName: "دوازدهمین امتحان مشترک فراگیر دستگاه‌های اجرایی کشور",
    organizer: "سازمان سنجش و آموزش کشور",
    resultFile: "/files/exam7-results.pdf",
    detailsFile: "/files/exam7-details.pdf",
    participants: 950,
    organization: "وزارت ارتباطات و فناوری اطلاعات",
    status: "در حال بررسی",
    resultDate: "1404/2/20",
    examDate: "1403/12/27",
  },
  {
    id: 14,
    examName: "دوازدهمین امتحان مشترک فراگیر دستگاه‌های اجرایی کشور",
    organizer: "سازمان سنجش و آموزش کشور",
    resultFile: "/files/exam7-results.pdf",
    detailsFile: "/files/exam7-details.pdf",
    participants: 950,
    organization: "سازمان ثبت احوال کشور",
    status: "تأیید شده",
    resultDate: "1404/2/20",
    examDate: "1403/12/27",
  },
  {
    id: 2,
    examName: "آزمون استخدامی کادر اداری قوه قضاییه",
    organizer: "سازمان سنجش و آموزش کشور",
    resultFile: "/files/exam2-results.pdf",
    detailsFile: "/files/exam2-details.pdf",
    participants: 850,
    organization: "قوه قضاییه",
    status: "عدم تأیید",
    resultDate: "1403/07/20",
    examDate: "1403/08/01",
  },
  {
    id: 3,
    examName:
      "آزمون استخدام نیروی پیمانی مشاغل عملیاتی آتش‌ نشانی شهرداری‌ های کشور",
    organizer: "مرکز آموزشی و پژوهشی رایانگان",
    resultFile: "/files/exam3-results.pdf",
    detailsFile: "/files/exam3-details.pdf",
    participants: 600,
    organization: "سازمان شهرداری ها و دهیاری های کشور",
    status: "عدم تأیید",
    resultDate: "1403/09/10",
    examDate: "1403/08/01",
  },
  {
    id: 4,
    examName: "ششمین آزمون مشترک فراگیر دستگاه‌های اجرایی کشور",
    organizer: "مرکز آموزشی و پژوهشی رایانگان",
    resultFile: "/files/exam4-results.pdf",
    detailsFile: "/files/exam4-details.pdf",
    participants: 950,
    organization: "سازمان اداری و استخدامی کشور",
    status: "تأیید شده",
    resultDate: "1403/11/25",
    examDate: "1403/09/01",
  },
  {
    id: 5,
    examName: "آزمون استخدامی تامین نیروی بانک شهر",
    organizer: "سازمان سنجش و آموزش کشور",
    resultFile: "/files/exam5-results.pdf",
    detailsFile: "/files/exam5-details.pdf",
    participants: 950,
    organization: "بانک مرکزی جمهوری اسلامی ایران",
    status: "تأیید شده",
    resultDate: "1403/11/25",
    examDate: "1403/09/10",
  },
  {
    id: 6,
    examName:
      "آزمون استخدامی نیروی انسانی سازمان زندان‌ها و اقدامات تامینی و تربیتی کشور",
    organizer: "شرکت ارزیابی تخصصی و آموزش کاریار",
    resultFile: "/files/exam6-results.pdf",
    detailsFile: "/files/exam6-details.pdf",
    participants: 950,
    organization: "سازمان زندانها و اقدامات تامینی و تربیتی کشور",
    status: "تأیید شده",
    resultDate: "1403/11/25",
    examDate: "1403/09/25",
  },
  {
    id: 7,
    examName:
      "آزمون به کارگیری نیرو در شرکت های طرف قرارداد شرکت برق منطقه‌ای اصفهان",
    organizer: "شرکت آزمون گستر",
    resultFile: "/files/exam1-results.pdf",
    detailsFile: "/files/exam1-details.pdf",
    participants: 1200,
    organization: "وزارت نیرو",
    status: "عدم تأیید",
    resultDate: "1403/05/15",
    examDate: "1400/03/20",
  },
  {
    id: 8,
    examName:
      "آزمون استخدام نيروی پيمانی مشاغل عملياتی آتش‌نشانی شهرداری اصفهان",
    organizer: "سازمان سنجش و آموزش کشور",
    resultFile: "/files/exam8-results.pdf",
    detailsFile: "/files/exam8-details.pdf",
    participants: 950,
    organization: "سازمان شهرداری ها و دهیاری های کشور",
    status: "تأیید شده",
    resultDate: "1403/11/25",
    examDate: "1403/12/23",
  },
  {
    id: 9,
    examName: "اولین آزمون استخدامی اختصاصی معلولان",
    organizer: "جهاد دانشگاهی",
    resultFile: "/files/exam9-results.pdf",
    detailsFile: "/files/exam9-details.pdf",
    participants: 950,
    organization: "سازمان بهزیستی کشور",
    status: "تأیید شده",
    resultDate: "1403/11/25",
    examDate: "1403/10/22",
  },
  {
    id: 10,
    examName: "آزمون بکارگیری نیروی قرارداد کار معین شهرداری‌ ها",
    organizer: "مرکز آموزشی و پژوهشی رایانگان",
    resultFile: "/files/exam10-results.pdf",
    detailsFile: "/files/exam10-details.pdf",
    participants: 950,
    organization: "سازمان شهرداری ها و دهیاری های کشور",
    status: "عدم تأیید",
    resultDate: "1403/11/25",
    examDate: "1403/09/22",
  },
  {
    id: 11,
    examName: "آزمون استخدامی شرکت فرودگاه‌ها و ناوبری هوایی ایران",
    organizer: "جهاد دانشگاهی",
    resultFile: "/files/exam11-results.pdf",
    detailsFile: "/files/exam11-details.pdf",
    participants: 950,
    organization: "وزارت راه و شهرسازی",
    status: "تأیید شده",
    resultDate: "1403/11/25",
    examDate: "1403/05/22",
  },
  {
    id: 12,
    examName: "آزمون استخدام نیروی انسانی وزارت امور خارجه جمهوری اسلامی",
    organizer: "سازمان سنجش و آموزش کشور",
    resultFile: "/files/exam12-results.pdf",
    detailsFile: "/files/exam12-details.pdf",
    participants: 950,
    organization: "وزارت امور خارجه",
    status: "عدم تأیید",
    resultDate: "1403/11/25",
    examDate: "1400/07/01",
  },
];
