export const initialExamAssessmentList = [
  {
    id: 1,
    examName: "چهاردهمین",
    examDate: "1404/05/01",
    totalCount: 1200,
    femaleCount: 720,
    maleCount: 480,
    assessmentFile: "/files/assessment-list1.xlsx",
    status: "درحال ثبت نام",
  },
  {
    id: 2,
    examName: "آزمون استخدامی وزارت بهداشت، درمان و آموزش پزشکی",
    examDate: "1404/06/01",
    totalCount: 850,
    femaleCount: 510,
    maleCount: 340,
    assessmentFile: "/files/assessment-list2.xlsx",
    status: "در انتظار",
  },
  {
    id: 3,
    examName:
      "آزمون به کارگیری نیرو در شرکت های طرف قرارداد شرکت برق منطقه‌ای اصفهان",
    examDate: "1400/03/20",
    totalCount: 600,
    femaleCount: 240,
    maleCount: 360,
    assessmentFile: "/files/assessment-list3.xlsx",
    status: "پایان آزمون",
  },
  {
    id: 4,
    examName: "آزمون استخدامی کادر اداری قوه قضاییه",
    examDate: "1403/08/01",
    totalCount: 950,
    femaleCount: 380,
    maleCount: 570,
    assessmentFile: "/files/assessment-list4.xlsx",
    status: "پایان آزمون",
  },
  {
    id: 5,
    examName: "آزمون استخدامی نیروی قراردادی سازمان ثبت اسناد و املاک کشور",
    examDate: "1404/02/30",
    totalCount: 700,
    femaleCount: 210,
    maleCount: 490,
    assessmentFile: "/files/assessment-list5.xlsx",
    status: "پایان ثبت نام",
  },
  {
    id: 6,
    examName:
      "آزمون استخدام نیروی پیمانی مشاغل عملیاتی آتش‌ نشانی شهرداری‌ های کشور",
    examDate: "1403/08/01",
    totalCount: 1100,
    femaleCount: 550,
    maleCount: 550,
    assessmentFile: "/files/assessment-list6.xlsx",
    status: "پایان آزمون",
  },
  {
    id: 7,
    examName: "ششمین آزمون مشترک فراگیر دستگاه‌های اجرایی کشور",
    examDate: "1403/09/01",
    totalCount: 450,
    femaleCount: 180,
    maleCount: 270,
    assessmentFile: "/files/assessment-list7.xlsx",
    status: "پایان آزمون",
  },
  {
    id: 8,
    examName: "آزمون استخدامی تامین نیروی بانک شهر",
    examDate: "1403/09/10",
    totalCount: 800,
    femaleCount: 320,
    maleCount: 480,
    assessmentFile: "/files/assessment-list8.xlsx",
    status: "پایان آزمون",
  },
  {
    id: 9,
    examName:
      "آزمون استخدامی نیروی انسانی سازمان زندان‌ها و اقدامات تامینی و تربیتی کشور",
    examDate: "1403/09/25",
    totalCount: 300,
    femaleCount: 120,
    maleCount: 180,
    assessmentFile: "/files/assessment-list9.xlsx",
    status: "پایان آزمون",
  },
  {
    id: 10,
    examName: "دوازدهمین امتحان مشترک فراگیر دستگاه‌های اجرایی کشور",
    examDate: "1403/11/27",
    totalCount: 650,
    femaleCount: 260,
    maleCount: 390,
    assessmentFile: "/files/assessment-list10.xlsx",
    status: "پایان آزمون",
  },
  {
    id: 11,
    examName:
      "آزمون استخدام نيروی پيمانی مشاغل عملياتی آتش‌نشانی شهرداری اصفهان",
    examDate: "1403/12/23",
    totalCount: 650,
    femaleCount: 260,
    maleCount: 390,
    assessmentFile: "/files/assessment-list11.xlsx",
    status: "پایان آزمون",
  },
  {
    id: 12,
    examName: "اولین آزمون استخدامی اختصاصی معلولان",
    examDate: "1403/10/22",
    totalCount: 700,
    femaleCount: 300,
    maleCount: 400,
    assessmentFile: "/files/assessment-list12.xlsx",
    status: "پایان آزمون",
  },
  {
    id: 13,
    examName: "آزمون بکارگیری نیروی قرارداد کار معین شهرداری‌ ها",
    examDate: "1403/09/22",
    totalCount: 250,
    femaleCount: 60,
    maleCount: 190,
    assessmentFile: "/files/assessment-list13.xlsx",
    status: "پایان آزمون",
  },
  {
    id: 14,
    examName: "آزمون استخدامی طرح شهید زین‌الدین (مرحله دوم)",
    examDate: "1404/08/01",
    totalCount: 650,
    femaleCount: 260,
    maleCount: 390,
    assessmentFile: "/files/assessment-list14.xlsx",
    status: "در انتظار",
  },
  {
    id: 15,
    examName: "آزمون جذب عمومی تصدی منصب قضا",
    examDate: "1404/07/01",
    totalCount: 650,
    femaleCount: 260,
    maleCount: 390,
    assessmentFile: "/files/assessment-list15.xlsx",
    status: "پایان ثبت نام",
  },
  {
    id: 16,
    examName: "آزمون استخدامی شرکت فرودگاه‌ها و ناوبری هوایی ایران",
    examDate: "1403/05/22",
    totalCount: 450,
    femaleCount: 160,
    maleCount: 290,
    assessmentFile: "/files/assessment-list16.xlsx",
    status: "پایان آزمون",
  },
  {
    id: 17,
    examName: "یازدهمین آزمون مشترک فراگیر دستگاه‌های اجرایی کشور",
    examDate: "1404/05/16",
    totalCount: 60,
    femaleCount: 26,
    maleCount: 39,
    assessmentFile: "/files/assessment-list17.xlsx",
    status: "درحال ثبت نام",
  },
  {
    id: 18,
    examName: "آزمون استخدامی شرکت مادرتخصصی عمران شهرهای جدید",
    examDate: "1404/07/01",
    totalCount: 550,
    femaleCount: 260,
    maleCount: 290,
    assessmentFile: "/files/assessment-list18.xlsx",
    status: "در انتظار",
  },
  {
    id: 19,
    examName: "آزمون استخدامی بانک توسعه صادرات ایران",
    examDate: "1404/07/01",
    totalCount: 850,
    femaleCount: 360,
    maleCount: 490,
    assessmentFile: "/files/assessment-list19.xlsx",
    status: "پایان ثبت نام",
  },
  {
    id: 20,
    examName: "آزمون استخدام نیروی انسانی وزارت امور خارجه جمهوری اسلامی",
    examDate: "1400/07/01",
    totalCount: 650,
    femaleCount: 260,
    maleCount: 390,
    assessmentFile: "/files/assessment-list20.xlsx",
    status: "پایان آزمون",
  },
];
