export const initialExecutives = [
  {
    id: 1,
    organizerName: "جهاد دانشگاهی",
    firstName: "حسین",
    lastName: "ولیسه رضایی",
    nationalCode: "1234567890",
    phoneNumber: "09123456789",
    domain: "حوزه تهران ۱",
    activityType: "آزمون گر",
    status: "در انتظار",
    hozeAzmoon: "مدرسه علامه حلی - تهران",
    performanceRating: "1",
  },
  {
    id: 2,
    organizerName: "مرکز آموزشی و پژوهشی رایانگان",
    firstName: "مریم",
    lastName: "احمدی",
    nationalCode: "0987654321",
    phoneNumber: "09354321098",
    domain: "حوزه اصفهان ۱",
    activityType: "آزمون گر",
    status: "ورود به قرنطینه",
    hozeAzmoon: "دبیرستان فرهیختگان - اصفهان",
    performanceRating: "3",
  },
  {
    id: 3,
    organizerName: "شرکت آزمون گستر",
    firstName: "رضا",
    lastName: "محمدی",
    nationalCode: "1122334455",
    phoneNumber: "09217654321",
    domain: "حوزه شیراز ۱",
    activityType: "آزمون گر",
    status: "پایان اجرا",
    hozeAzmoon: "دانشگاه شیراز - ساختمان علوم",
    performanceRating: "4",
  },
  {
    id: 4,
    organizerName: "سازمان سنجش و آموزش کشور",
    firstName: "زهرا",
    lastName: "کریمی",
    nationalCode: "5566778899",
    phoneNumber: "09198765432",
    domain: "حوزه مشهد ۱",
    activityType: "آزمون بان",
    status: "خروج از قرنطینه",
    hozeAzmoon: "مدرسه نمونه امام رضا - مشهد",
    performanceRating: "3",
  },
  {
    id: 5,
    organizerName: "جهاد دانشگاهی",
    firstName: "علی",
    lastName: "رضوی",
    nationalCode: "9876543210",
    phoneNumber: "09129876543",
    domain: "حوزه تبریز ۱",
    activityType: "آزمون بان",
    status: "ورود به قرنطینه",
    hozeAzmoon: "دانشگاه تبریز - دانشکده فنی",
    performanceRating: "2",
  },
  {
    id: 6,
    organizerName: "مرکز آموزشی و پژوهشی رایانگان",
    firstName: "سارا",
    lastName: "محسن‌زاده",
    nationalCode: "4567891234",
    phoneNumber: "09361234567",
    domain: "حوزه کرج ۱",
    activityType: "آزمون گر",
    status: "پایان اجرا",
    hozeAzmoon: "دانشگاه آزاد اسلامی واحد کرج",
    performanceRating: "3",
  },
  {
    id: 7,
    organizerName: "شرکت آزمون گستر",
    firstName: "محمد",
    lastName: "اکبری",
    nationalCode: "3216549870",
    phoneNumber: "09219876543",
    domain: "حوزه قم ۱",
    activityType: "آزمون بان",
    status: "در انتظار",
    hozeAzmoon: "دبیرستان مهدی موعود - قم",
    performanceRating: "3",
  },
  {
    id: 8,
    organizerName: "سازمان سنجش و آموزش کشور",
    firstName: "فاطمه",
    lastName: "حسینی",
    nationalCode: "6543217890",
    phoneNumber: "09127654321",
    domain: "حوزه اهواز ۱",
    activityType: "آزمون گر",
    status: "خروج از قرنطینه",
    hozeAzmoon: "دانشگاه شهید چمران اهواز",
    performanceRating: "1",
  },
  {
    id: 9,
    organizerName: "جهاد دانشگاهی",
    firstName: "امیر",
    lastName: "قاسمی",
    nationalCode: "7894561230",
    phoneNumber: "09123459876",
    domain: "حوزه رشت ۱",
    activityType: "آزمون بان",
    status: "پایان اجرا",
    hozeAzmoon: "مدرسه البرز - رشت",
    performanceRating: "3",
  },
  {
    id: 10,
    organizerName: "مرکز آموزشی و پژوهشی رایانگان",
    firstName: "نرگس",
    lastName: "علوی",
    nationalCode: "1472583690",
    phoneNumber: "09359876543",
    domain: "حوزه یزد ۱",
    activityType: "مخزن دار",
    status: "ورود به قرنطینه",
    hozeAzmoon: "دانشگاه یزد - دانشکده علوم انسانی",
    performanceRating: "4",
  },
];
