export const initialSupplementaryResults = [
  {
    id: 1,
    assessmentName:
      "آزمون به کارگیری نیرو در شرکت های طرف قرارداد شرکت برق منطقه‌ای اصفهان",
    organization: "وزارت نیرو",
    job: "اپراتور فوق توزیع",
    organizer: "شرکت آزمون گستر",
    date: "1403/05/10",
    resultDate: "1403/06/10",
    resultFile: "/files/assessment1-results.pdf",
    status: "تأیید نهایی",
    Province:"اصفهان",
  },
  {
    id: 2,
    assessmentName: "آزمون استخدامی کادر اداری قوه قضاییه",
    organization: "قوه قضاییه",
    job: "متصدی امور دفتری",
    organizer: "سازمان سنجش و آموزش کشور",
    date: "1403/06/15",
    resultDate: "1403/08/10",
    resultFile: "/files/assessment2-results.pdf",
    status: "تأیید سازمان اداری و استخدامی",
    Province:"تهران",
  },
  {
    id: 3,
    assessmentName:
      "آزمون استخدام نیروی پیمانی مشاغل عملیاتی آتش‌ نشانی شهرداری‌ های کشور",
    organization: "سازمان شهرداری ها و دهیاری های کشور",
    job: "آتش‌نشان",
    organizer: "مرکز آموزشی و پژوهشی رایانگان",
    date: "1403/07/20",
    resultDate: "1403/09/13",
    resultFile: "/files/assessment3-results.pdf",
    status: "در حال اجرا",
    Province:"تهران",
  },
  {
    id: 4,
    assessmentName: "آزمون استخدامی تامین نیروی بانک شهر",
    organization: "بانک مرکزی جمهوری اسلامی ایران",
    job: "بانکدار (متصدی دریافت و پرداخت - تحویلدار)",
    organizer: "سازمان سنجش و آموزش کشور",
    date: "1403/08/05",
    resultDate: "1403/10/16",
    resultFile: "/files/assessment4-results.pdf",
    status: "ارسال به سازمان اداری و استخدامی",
    Province:"تهران",
  },
  {
    id: 5,
    assessmentName:
      "آزمون استخدامی نیروی انسانی سازمان زندانها و اقدامات تامینی و تربیتی کشور",
    organization: "سازمان زندانها و اقدامات تامینی و تربیتی کشور",
    job: "مامور گارد انتظامات زندانها",
    organizer: "شرکت ارزیابی تخصصی و آموزش کاریار",
    date: "1403/09/10",
    resultDate: "1403/11/25",
    resultFile: "/files/assessment5-results.pdf",
    status: "در حال اجرا",
    Province:"تهران",
  },
  {
    id: 6,
    assessmentName:
      "آزمون استخدام نيروی پيمانی مشاغل عملياتی آتش‌نشانی شهرداری اصفهان",
    organization: "سازمان شهرداری ها و دهیاری های کشور",
    job: "آتش‌نشان",
    organizer: "سازمان سنجش و آموزش کشور",
    date: "1403/10/15",
    resultDate: "1403/12/19",
    resultFile: "/files/assessment6-results.pdf",
    status: "تأیید نهایی",
    Province:"اصفهان",
  },
  {
    id: 7,
    assessmentName: "اولین آزمون استخدامی اختصاصی معلولان",
    organization: "سازمان بهزیستی کشور",
    job: "کارشناس اداری",
    organizer: "جهاد دانشگاهی",
    date: "1403/11/20",
    resultDate: "1404/02/10",
    resultFile: "/files/assessment7-results.pdf",
    status: "تأیید نهایی",
    Province:"تهران",
  },
  {
    id: 8,
    assessmentName: "آزمون بکارگیری نیروی قرارداد کار معین شهرداری‌ ها",
    organization: "سازمان شهرداری ها و دهیاری های کشور",
    job: "حسابدار",
    organizer: "شرکت امتحان برتر",
    date: "1403/12/25",
    resultDate: "1404/02/19",
    resultFile: "/files/assessment8-results.pdf",
    status: "در حال اجرا",
    Province:"تهران",
  },
  {
    id: 9,
    assessmentName: "آزمون استخدامی شرکت فرودگاه‌ها و ناوبری هوایی ایران",
    organization: "وزارت راه و شهرسازی",
    job: "مهندس هوافضا",
    organizer: "جهاد دانشگاهی",
    date: "1404/01/30",
    resultDate: "1404/03/03",
    resultFile: "/files/assessment9-results.pdf",
    status: "ارسال به سازمان اداری و استخدامی",
    Province:"تهران",
  },
  {
    id: 10,
    assessmentName: "آزمون استخدام نیروی انسانی وزارت امور خارجه جمهوری اسلامی",
    organization: "وزارت امور خارجه",
    job: "مترجم",
    organizer: "سازمان سنجش و آموزش کشور",
    date: "1404/02/05",
    resultDate: "1404/05/10",
    resultFile: "/files/assessment10-results.pdf",
    status: "تأیید سازمان اداری و اقتصادی",
    Province:"تهران",
  },
];
