import { useState } from "react";

const initialExecutiveBodies = [
  {
    id: "1",
    name: "وزارت نیرو",
    parent: null,
    image: "/assets/images/niru.png",
    subCount: 21,
    subDisplay: "نمایش",
  },
  {
    id: "2",
    name: "شرکت مدیریت منابع آب ایران",
    parent: "1",
    image: "default.png",
    subCount: 3,
    subDisplay: "نمایش",
  },
  {
    id: "3",
    name: "شرکت تولید نیروی برق حرارتی",
    parent: "1",
    image: "default.png",
    subCount: 4,
    subDisplay: "نمایش",
  },
  {
    id: "4",
    name: "شرکت توانیر",
    parent: "1",
    image: "default.png",
    subCount: 8,
    subDisplay: "نمایش",
  },
  {
    id: "5",
    name: "سازمان انرژی های تجدیدپذیر و بهره وری انرژی برق(ساتبا)",
    parent: "1",
    image: "default.png",
    subCount: 1,
    subDisplay: "نمایش",
  },
  {
    id: "6",
    name: "شرکت مهندسی آب و فاضلاب کشور",
    parent: "1",
    image: "default.png",
    subCount: 1,
    subDisplay: "نمایش",
    activities: "مدیریت آب و فاضلاب",
  },
  {
    id: "7",
    name: "شرکت آب منطقه ای آذربایجان غربی",
    parent: "2",
    image: "default.png",
    subCount: 0,
    subDisplay: "نمایش",
    activities: "مدیریت منابع آب منطقه‌ای",
  },
  {
    id: "8",
    name: "شرکت آب منطقه ای استان خوزستان",
    parent: "2",
    image: "default.png",
    subCount: 0,
    subDisplay: "نمایش",
    activities: "مدیریت منابع آب منطقه‌ای",
  },
  {
    id: "9",
    name: "شرکت مدیریت تولید نیروی برق دماوند",
    parent: "3",
    image: "default.png",
    subCount: 0,
    subDisplay: "نمایش",
    activities: "تولید برق",
  },
  {
    id: "10",
    name: "شرکت مدیریت تولید نیروی برق شهید رجایی",
    parent: "3",
    image: "default.png",
    subCount: 0,
    subDisplay: "نمایش",
    activities: "تولید برق",
  },
  {
    id: "11",
    name: "شرکت آریا ترانسفو قدرت",
    parent: "4",
    image: "default.png",
    subCount: 0,
    subDisplay: "نمایش",
    activities: "تولید تجهیزات برق",
  },
  {
    id: "12",
    name: "شرکت تولید نیروی برق لوشان",
    parent: "3",
    image: "default.png",
    subCount: 0,
    subDisplay: "نمایش",
    activities: "تولید برق",
  },
  {
    id: "13",
    name: "سازمان انرژی های تجدید پذیر و بهره وری انرژی برق",
    parent: "5",
    image: "default.png",
    subCount: 0,
    subDisplay: "نمایش",
    activities: "انرژی تجدیدپذیر",
  },
  {
    id: "14",
    name: "شرکت پیشگامان فن اندیش تهران",
    parent: "4",
    image: "default.png",
    subCount: 0,
    subDisplay: "نمایش",
    activities: "خدمات فنی",
  },
  {
    id: "15",
    name: "نیروگاه سیکل ترکیبی جهرم",
    parent: "3",
    image: "default.png",
    subCount: 0,
    subDisplay: "نمایش",
    activities: "تولید برق",
  },
  {
    id: "16",
    name: "شرکت میهن نور کوشا",
    parent: "4",
    image: "default.png",
    subCount: 0,
    subDisplay: "نمایش",
    activities: "خدمات برق",
  },
  {
    id: "17",
    name: "شرکت کاویان سازه آژند",
    parent: "4",
    image: "default.png",
    subCount: 0,
    subDisplay: "نمایش",
    activities: "خدمات فنی",
  },
  {
    id: "18",
    name: "شرکت توزیع نیروی برق البرز(پیمان صنعت نیوساد)",
    parent: "4",
    image: "default.png",
    subCount: 0,
    subDisplay: "نمایش",
    activities: "توزیع نیروی برق",
  },
  {
    id: "19",
    name: "شرکت توزیع نیروی برق استان سیستان و بلوچستان",
    parent: "4",
    image: "default.png",
    subCount: 0,
    subDisplay: "نمایش",
    activities: "توزیع نیروی برق",
  },
  {
    id: "20",
    name: "شرکت توزیع نیروی برق استان گیلان",
    parent: "4",
    image: "default.png",
    subCount: 0,
    subDisplay: "نمایش",
    activities: "توزیع نیروی برق",
  },
  {
    id: "21",
    name: "شرکت آب و فاضلاب شهر شیراز",
    parent: "6",
    image: "default.png",
    subCount: 0,
    subDisplay: "نمایش",
    activities: "مدیریت آب و فاضلاب",
  },
  {
    id: "22",
    name: "شرکت توسعه منابع آب و نیروی ایران",
    parent: "2",
    image: "default.png",
    subCount: 0,
    subDisplay: "نمایش",
    activities: "توسعه منابع آب",
  },
  {
    id: "23",
    name: "شرکت توزیع نیروی برق استان ایلام",
    parent: "4",
    image: "default.png",
    subCount: 0,
    subDisplay: "نمایش",
    activities: "توزیع نیروی برق",
  },
  {
    id: "24",
    name: "سازمان بهزیستی کشور",
    parent: null,
    image: "default.png",
    subCount: 4,
    subDisplay: "نمایش",
  },
  {
    id: "25",
    name: "شیرخوارگاه و خانه نوباوگان خاتم الانبیاء خراسان جنوبی",
    parent: "24",
    image: "default.png",
    subCount: 0,
    subDisplay: "نمایش",
    activities: "خدمات اجتماعی",
  },
  {
    id: "26",
    name: "مرکز اورژانس خدمات اجتماعی الزهرا خراسان جنوبی",
    parent: "24",
    image: "default.png",
    subCount: 0,
    subDisplay: "نمایش",
    activities: "خدمات اجتماعی",
  },
  {
    id: "28",
    name: "خانه کودکان خیابانی فدائیان اسلام خراسان رضوی",
    parent: "24",
    image: "default.png",
    subCount: 0,
    subDisplay: "نمایش",
    activities: "خدمات اجتماعی",
  },
  {
    id: "29",
    name: "شیرخوارگاه و خانه نوباوگان حضرت علی اصغر خراسان رضوی",
    parent: "24",
    image: "default.png",
    subCount: 0,
    subDisplay: "نمایش",
    activities: "خدمات اجتماعی",
  },
];

export const useExecutiveBodiesData = () => {
  const [data, setData] = useState(initialExecutiveBodies);

  return {
    data,
    setData,
  };
};
