const users = [
  {
    UserID: "1",
    username: "admin",
    password: "123",
    role: "رئیس سازمان اداری و استخدامی",
    roleId: "1",
    firstName: "پشتیبان",
    lastName: "1",
    UserEmail: "",
    UserPhoneNumber: "",
    UserNationalCode: "",
    UserPostRef: null,
    UserRankRef: null,
    UserOrganizerRef: null,
    UserAnalyzeOrganizerRef: null,
    UserExecutiveBodyRef: null,
    UserReportGenerated: null,
    UserImage: "avatar1.png",
    UserFirstTime: "N",
    UserRole: "1",
    UserIsOnline: "N",
    UserLastActivity: null,
    UserAdminNumber: 1,
  },
  {
    UserID: "2",
    username: "sysmanager",
    password: "123",
    role: "مدیر سیستم",
    roleId: "1",
    firstName: "پشتیبان",
    lastName: "2",
    UserEmail: "",
    UserPhoneNumber: "",
    UserNationalCode: "",
    UserPostRef: null,
    UserRankRef: null,
    UserOrganizerRef: null,
    UserAnalyzeOrganizerRef: null,
    UserExecutiveBodyRef: null,
    UserReportGenerated: null,
    UserImage: "avatar1.png",
    UserFirstTime: "N",
    UserRole: "1",
    UserIsOnline: "Y",
    UserLastActivity: null,
    UserAdminNumber: 2,
  },
  {
    UserID: "3",
    username: "SAZMAN",
    password: "123",
    role: "کاربر سازمان اداری و استخدامی",
    roleId: "2",
    firstName: "محمد",
    lastName: "بیات",
    UserEmail: "sazman@gmail.com",
    UserPhoneNumber: "09108589643",
    UserNationalCode: "0311190057",
    UserPostRef: "17",
    UserRankRef: "3",
    UserOrganizerRef: null,
    UserAnalyzeOrganizerRef: null,
    UserExecutiveBodyRef: null,
    UserReportGenerated: null,
    UserImage: "avatar2.png",
    UserFirstTime: "N",
    UserRole: "2",
    UserIsOnline: "Y",
    UserLastActivity: "2025-05-01 16:30:37",
    UserAdminNumber: null,
  },
  {
    UserID: "4",
    username: "v.niru",
    password: "123",
    role: "وزارت نیرو",
    roleId: "3",
    firstName: "علی",
    lastName: "محمدی",
    UserEmail: "setad@gmail.com",
    UserPhoneNumber: "09108589643",
    UserNationalCode: "0311190057",
    UserPostRef: "4",
    UserRankRef: "4",
    UserOrganizerRef: null,
    UserAnalyzeOrganizerRef: null,
    UserExecutiveBodyRef: null,
    UserReportGenerated: null,
    UserImage: "avatar3.png",
    UserFirstTime: "N",
    UserRole: "3",
    UserIsOnline: "N",
    UserLastActivity: "2025-05-01 14:59:28",
    UserAdminNumber: null,
  },
  {
    UserID: "5",
    username: "tabe",
    password: "123",
    role: "دستگاه تابعه",
    roleId: "4",
    firstName: "صادق",
    lastName: "مرادی",
    UserEmail: "tabe@gmail.com",
    UserPhoneNumber: "09108589643",
    UserNationalCode: "0311190057",
    UserPostRef: "5",
    UserRankRef: "5",
    UserOrganizerRef: null,
    UserAnalyzeOrganizerRef: null,
    UserExecutiveBodyRef: null,
    UserReportGenerated: null,
    UserImage: "avatar4.png",
    UserFirstTime: "N",
    UserRole: "4",
    UserIsOnline: "N",
    UserLastActivity: "2025-05-01 15:01:46",
    UserAdminNumber: null,
  },
  {
    UserID: "6",
    username: "MOJRI",
    password: "123",
    role: "شركت تعاوني پژوهشگران رايانگان فرديس (مجری آزمون کتبی)",
    roleId: "5",
    firstName: "رضا",
    lastName: "رحمانی",
    UserEmail: "mojri@gmail.com",
    UserPhoneNumber: "09108689664",
    UserNationalCode: "0311190057",
    UserPostRef: "2",
    UserRankRef: "6",
    UserOrganizerRef: "1",
    UserAnalyzeOrganizerRef: null,
    UserExecutiveBodyRef: null,
    UserReportGenerated: null,
    UserImage: "avatar5.png",
    UserFirstTime: "N",
    UserRole: "5",
    UserIsOnline: "N",
    UserLastActivity: "2025-05-01 14:51:20",
    UserAdminNumber: null,
  },
  {
    UserID: "7",
    username: "ARZYAB",
    password: "123",
    role: "ارزیاب",
    roleId: "7",
    firstName: "جواد",
    lastName: "رضائی",
    UserEmail: "arzyab@gmail.com",
    UserPhoneNumber: "09108589643",
    UserNationalCode: "0311190057",
    UserPostRef: "7",
    UserRankRef: "9",
    UserOrganizerRef: null,
    UserAnalyzeOrganizerRef: null,
    UserExecutiveBodyRef: null,
    UserReportGenerated: null,
    UserImage: "avatar7.png",
    UserFirstTime: "N",
    UserRole: "7",
    UserIsOnline: "N",
    UserLastActivity: "2025-05-01 16:33:23",
    UserAdminNumber: null,
  },
  {
    UserID: "8",
    username: "KANOON",
    password: "123",
    role: "شركت تعاوني پژوهشگران رايانگان فرديس (مجری ارزیابی تکمیلی)",
    roleId: "6",
    firstName: "مینا",
    lastName: "محمدی",
    UserEmail: "kanoon@gmail.com",
    UserPhoneNumber: "09108589643",
    UserNationalCode: "0311190057",
    UserPostRef: "3",
    UserRankRef: "7",
    UserOrganizerRef: null,
    UserAnalyzeOrganizerRef: null,
    UserExecutiveBodyRef: null,
    UserReportGenerated: null,
    UserImage: "avatar6.png",
    UserFirstTime: "N",
    UserRole: "6",
    UserIsOnline: "Y",
    UserLastActivity: "2025-05-01 16:33:01",
    UserAdminNumber: null,
  },
];

export default users;
