export const samplePermitRequests = [
  {
    id: 1,
    requestNumber: "PR-001",
    status: "تأیید شده",
    organization: "وزارت آموزش و پرورش",
    subOrganization: "اداره کل تهران",
    employmentType: "رسمی",
    scoreRatio: "70%",
    registrationDate: "1403/01/15",
    hiringCapacity: 120,
    capacityMultiplier: "3 برابر",
    confirmationDate: "1403/02/01",
  },
  {
    id: 2,
    requestNumber: "PR-002",
    status: "در انتظار",
    organization: "وزارت بهداشت",
    subOrganization: "دانشگاه علوم پزشکی",
    employmentType: "پیمانی",
    scoreRatio: "60%",
    registrationDate: "1403/02/10",
    hiringCapacity: 80,
    capacityMultiplier: "2 برابر",
    confirmationDate: "1403/03/01",
  },
  {
    id: 3,
    requestNumber: "PR-003",
    status: "رد شده",
    organization: "وزارت نیرو",
    subOrganization: "شرکت برق منطقه‌ای",
    employmentType: "قراردادی",
    scoreRatio: "50%",
    registrationDate: "1403/03/05",
    hiringCapacity: 50,
    capacityMultiplier: "4 برابر",
    confirmationDate: "1403/04/01",
  },
  {
    id: 4,
    requestNumber: "PR-004",
    status: "تأیید شده",
    organization: "وزارت آموزش و پرورش",
    subOrganization: "اداره کل تهران",
    employmentType: "رسمی",
    scoreRatio: "70%",
    registrationDate: "1403/04/15",
    hiringCapacity: 150,
    capacityMultiplier: "3 برابر",
    confirmationDate: "1403/05/01",
  },
  {
    id: 5,
    requestNumber: "PR-005",
    status: "در انتظار",
    organization: "وزارت بهداشت",
    subOrganization: "دانشگاه علوم پزشکی",
    employmentType: "پیمانی",
    scoreRatio: "60%",
    registrationDate: "1403/05/10",
    hiringCapacity: 90,
    capacityMultiplier: "2 برابر",
    confirmationDate: "1403/06/01",
  },
];
