export const initialSupplementaryDocs = [
  {
    id: 1,
    examName:
      "آزمون به کارگیری نیرو در شرکت های طرف قرارداد شرکت برق منطقه‌ای اصفهان",
    organization: "وزارت نیرو",
    job: "اپراتور فوق توزیع",
    organizer: "شرکت آزمون گستر",
    examDate: "1403/12/15",
    detailsFile: "/files/supplementary1-details.pdf",
    status: "بررسی نشده",
    Province: "اصفهان",
    MultipleCapacity: "3",
  },
  {
    id: 2,
    examName: "آزمون استخدامی کادر اداری قوه قضاییه",
    organization: "قوه قضاییه",
    job: "متصدی امور دفتری",
    organizer: "سازمان سنجش و آموزش کشور",
    examDate: "1403/12/20",
    detailsFile: "/files/supplementary2-details.pdf",
    status: "بررسی نشده",
    Province: "تهران",
    MultipleCapacity: "3",
  },
  {
    id: 3,
    examName:
      "آزمون استخدام نیروی پیمانی مشاغل عملیاتی آتش‌ نشانی شهرداری‌ های کشور",
    organization: "سازمان شهرداری ها و دهیاری های کشور",
    job: "آتش‌نشان",
    organizer: "مرکز آموزشی و پژوهشی رایانگان",
    examDate: "1403/12/25",
    detailsFile: "/files/supplementary3-details.pdf",
    status: "تأیید شده",
    Province: "تهران",
    MultipleCapacity: "5",
  },
  {
    id: 4,
    examName: "آزمون استخدامی تامین نیروی بانک شهر",
    organization: "بانک مرکزی جمهوری اسلامی ایران",
    job: "بانکدار (متصدی دریافت و پرداخت - تحویلدار)",
    organizer: "سازمان سنجش و آموزش کشور",
    examDate: "1404/01/05",
    detailsFile: "/files/supplementary4-details.pdf",
    status: "عدم تأیید",
    Province: "تهران",
    MultipleCapacity: "5",
  },
  {
    id: 5,
    examName:
      "آزمون استخدامی نیروی انسانی سازمان زندانها و اقدامات تامینی و تربیتی کشور",
    organization: "سازمان زندانها و اقدامات تامینی و تربیتی کشور",
    job: "مامور گارد انتظامات زندانها",
    organizer: "شرکت ارزیابی تخصصی و آموزش کاریار",
    examDate: "1404/01/10",
    detailsFile: "/files/supplementary5-details.pdf",
    status: "تأیید شده",
    Province: "تهران",
    MultipleCapacity: "3",
  },
  {
    id: 6,
    examName:
      "آزمون استخدام نيروی پيمانی مشاغل عملياتی آتش‌نشانی شهرداری اصفهان",
    organization: "سازمان شهرداری ها و دهیاری های کشور",
    job: "آتش‌نشان",
    organizer: "سازمان سنجش و آموزش کشور",
    examDate: "1404/01/15",
    detailsFile: "/files/supplementary6-details.pdf",
    status: "عدم تأیید",
    Province: "اصفهان",
    MultipleCapacity: "5",
  },
  {
    id: 7,
    examName: "اولین آزمون استخدامی اختصاصی معلولان",
    organization: "سازمان بهزیستی کشور",
    job: "کارشناس اداری",
    organizer: "جهاد دانشگاهی",
    examDate: "1404/01/20",
    detailsFile: "/files/supplementary7-details.pdf",
    status: "عدم تأیید",
    Province: "تهران",
    MultipleCapacity: "3",
  },
  {
    id: 8,
    examName: "آزمون بکارگیری نیروی قرارداد کار معین شهرداری‌ ها",
    organization: "سازمان شهرداری ها و دهیاری های کشور",
    job: "حسابدار",
    organizer: "شرکت امتحان برتر",
    examDate: "1404/01/25",
    detailsFile: "/files/supplementary8-details.pdf",
    status: "تأیید شده",
    Province: "تهران",
    MultipleCapacity: "5",
  },
  {
    id: 9,
    examName: "آزمون استخدامی شرکت فرودگاه‌ها و ناوبری هوایی ایران",
    organization: "وزارت راه و شهرسازی",
    job: "مهندس هوافضا",
    organizer: "جهاد دانشگاهی",
    examDate: "1404/02/01",
    detailsFile: "/files/supplementary9-details.pdf",
    status: "عدم تأیید",
    Province: "البرز",
    MultipleCapacity: "3",
  },
  {
    id: 10,
    examName: "آزمون استخدام نیروی انسانی وزارت امور خارجه جمهوری اسلامی",
    organization: "وزارت امور خارجه",
    job: "مترجم",
    organizer: "سازمان سنجش و آموزش کشور",
    examDate: "1404/02/05",
    detailsFile: "/files/supplementary10-details.pdf",
    status: "تأیید شده",
    Province: "تهران",
    MultipleCapacity: "3",
  },
];
