export const examData = [
    {
    id: 1,
    examName: "چهاردهمین",
    examDate: "1404/05/01",
    organizer: "سازمان سنجش و آموزش کشور",
    status: "در قرنطینه",
    lessons: [
      { type: "عمومی", name: "معارف اسلامی", icon: "fa-calculator" },
      { type: "عمومی", name: "زبان و ادبیات فارسی", icon: "fa-chart-line" },
      { type: "عمومی", name: "معلومات عمومی", icon: "fa-chart-line" },
      { type: "عمومی", name: "زبان انگلیسی عمومی", icon: "fa-chart-line" },
      { type: "عمومی", name: "هوش و توانمندی‌های ذهنی", icon: "fa-chart-line" },
      { type: "عمومی", name: "فناوری اطلاعات ICDL", icon: "fa-chart-line" },
      {
        type: "عمومی",
        name: "آشنایی با قوانین و مقررات اداری",
        icon: "fa-chart-line",
      },
      {
        type: "اختصاصی",
        name: "ماموریت، اهداف و ارکان سازمان سنجش آموزش کشور ",
        icon: "fa-chart-line",
      },
      {
        type: "اختصاصی",
        name: "سیاست های کلی ایجاد تحول در آموزش و پرورش",
        icon: "fa-chart-line",
      },
      {
        type: "اختصاصی",
        name: "سند تحول بنیادین آموزش و پرورش",
        icon: "fa-users",
      },
      {
        type: "اختصاصی",
        name: "آیین نامه اجرایی مدارس، مصوب 1400 شورای عالی آموزش و پرورش",
        icon: "fa-users",
      },
    ],
  },
  {
    id: 2,
    examName: "آزمون استخدامی تامین نیروی بانک شهر",
    examDate: "1403/09/10",
    organizer: "سازمان سنجش و آموزش کشور",
    status: "در دسترس",
    lessons: [
      { type: "عمومی", name: "زبان و ادبیات فارسی", icon: "fa-calculator" },
      { type: "عمومی", name: "معارف اسلامی", icon: "fa-chart-line" },
      { type: "عمومی", name: "زبان انگلیسی عمومی", icon: "fa-chart-line" },
      {
        type: "عمومی",
        name: "اطلاعات عمومی، دانش اجتماعی و حقوقی",
        icon: "fa-chart-line",
      },
      { type: "عمومی", name: "هوش و استعداد تحصیلی", icon: "fa-chart-line" },
      { type: "عمومی", name: "فناوری اطلاعات", icon: "fa-book" },
      { type: "اختصاصی", name: "اصول و مبانی حسابداری", icon: "fa-chart-line" },
      { type: "اختصاصی", name: "حسابداری مالی", icon: "fa-users" },
      { type: "اختصاصی", name: "حسابداری دولتی", icon: "fa-users" },
      { type: "اختصاصی", name: "حسابداری بهای تمام شده", icon: "fa-users" },
      { type: "اختصاصی", name: "حسابداری مدیریت", icon: "fa-users" },
      { type: "اختصاصی", name: "اصول و مبانی بانکداری", icon: "fa-users" },
      { type: "اختصاصی", name: "عملیات بانکی", icon: "fa-users" },
      { type: "اختصاصی", name: "نظام های پولی و بانکی", icon: "fa-users" },
      { type: "اختصاصی", name: "بازار پول و سرمایه", icon: "fa-users" },
      { type: "اختصاصی", name: "تجارت بین الملل", icon: "fa-users" },
      { type: "اختصاصی", name: "مقررات بانکی", icon: "fa-users" },
      { type: "اختصاصی", name: "اقتصاد کلان", icon: "fa-users" },
      { type: "اختصاصی", name: "اقتصاد خرد", icon: "fa-users" },
      { type: "اختصاصی", name: "آمار و احتمال", icon: "fa-users" },
    ],
  },
  {
    id: 3,
    examName:
      "آزمون به کارگیری نیرو در شرکت های طرف قرارداد شرکت برق منطقه‌ای اصفهان",
    organizer: "شرکت آزمون گستر",
    examDate: "1400/03/20",
    status: "در دسترس",
    lessons: [
      {
        type: "عمومی",
        name: "فناوری اطلاعات (مهارتهای هفتگانه L.D.C.I )",
        icon: "fa-calculator",
      },
      { type: "عمومی", name: "ریاضی و آمار مقدماتی", icon: "fa-chart-line" },
      {
        type: "عمومی",
        name: "زبان و ادبیات فارسی و آیین نگارش",
        icon: "fa-chart-line",
      },
      { type: "عمومی", name: "معارف اسلامی", icon: "fa-chart-line" },
      { type: "عمومی", name: "زبان انگلیسی ـ عمومی", icon: "fa-chart-line" },
      {
        type: "عمومی",
        name: "اطلاعاتAgo عمومی، دانش اجتماعی و قانون اساسی",
        icon: "fa-chart-line",
      },
      { type: "عمومی", name: "هوش و استعداد شغلی", icon: "fa-chart-line" },
      {
        type: "اختصاصی",
        name: "مدارهای الکتریکی 1 و 2",
        icon: "fa-chart-line",
      },
      { type: "اختصاصی", name: "الکترونیک 1 و 2", icon: "fa-chart-line" },
      { type: "اختصاصی", name: "سیستم های دیجیتال", icon: "fa-users" },
      { type: "اختصاصی", name: "الکترومغناطیس", icon: "fa-users" },
    ],
  },

];

export const sampleQuestions = [
  {
    id: 1,
    question: "پایتخت ایران کجاست؟",
    optionA: "تهران",
    optionB: "اصفهان",
    optionC: "شیراز",
    optionD: "مشهد",
    answer: "الف",
    level: "آسان",
  },
  {
    id: 2,
    question: "بزرگ‌ترین قاره جهان کدام است؟",
    optionA: "آفریقا",
    optionB: "آسیا",
    optionC: "اروپا",
    optionD: "آمریکا",
    answer: "ب",
    level: "متوسط",
  },
];
