export const sampleEvaluations = [
  {
    id: 1,
    examTitle:
      "آزمون به کارگیری نیرو در شرکت های طرف قرارداد شرکت برق منطقه‌ای اصفهان",
    organization: "وزارت نیرو",
    job: "اپراتور فوق توزیع",
    group: "گروه ج",
    examDate: "1400/04/20",
    examTime: "09:00",
    examEndDate: "1400/04/23", // 3 روز بعد
    examEndTime: "14:00",
    examineesCount: 25,
    evaluatorsCount: 5,
    examinees: "/assets/files/مستندات.txt",
    evaluators: "/assets/files/مستندات.txt",
    province: "اصفهان",
    City: "میمه",
    location: "ایستگاه ۶۳ کیلوولت میمه",
    stauss: "درحال اجرا",
    scheduleFile: "/assets/schedules/schedule_3.xlsx",
  },
  {
    id: 2,
    examTitle: "آزمون استخدامی کادر اداری قوه قضاییه",
    organization: "قوه قضاییه",
    job: "متصدی امور دفتری",
    group: "گروه الف",
    examDate: "1404/01/05",
    examTime: "11:00",
    examEndDate: "1404/01/07", // 2 روز بعد
    examEndTime: "12:00",
    examineesCount: 40,
    evaluatorsCount: 8,
    examinees: "/assets/files/مستندات.txt",
    evaluators: "/assets/files/مستندات.txt",
    province: "خراسان شمالی",
    City: "اسفراین",
    location: "دادگاه بخش بام و صفی آباد",
    stauss: "در انتظار اعلام نتایج",
    scheduleFile: "/assets/schedules/schedule_3.xlsx",
  },
  {
    id: 3,
    examTitle:
      "آزمون استخدام نیروی پیمانی مشاغل عملیاتی آتش‌ نشانی شهرداری‌ های کشور",
    organization: "سازمان شهرداری ها و دهیاری های کشور",
    job: "آتشنشان",
    group: "گروه ب",
    examDate: "1404/01/10",
    examTime: "08:30",
    examEndDate: "1404/01/13", // 3 روز بعد
    examEndTime: "15:00",
    examineesCount: 30,
    evaluatorsCount: 6,
    examinees: "/assets/files/مستندات.txt",
    evaluators: "/assets/files/مستندات.txt",
    province: "تهران",
    City: "دماوند",
    location: "رودهن",
    stauss: "پایان یافته",
    scheduleFile: "/assets/schedules/schedule_3.xlsx",
  },
  {
    id: 4,
    examTitle: "آزمون استخدامی تامین نیروی بانک شهر",
    organization: "بانک مرکزی جمهوری اسلامی ایران",
    job: "بانکدار (متصدی دریافت و پرداخت - تحویلدار)",
    group: "گروه ب",
    examDate: "1404/01/10",
    examTime: "08:30",
    examEndDate: "1404/01/12", // 2 روز بعد
    examEndTime: "14:00",
    examineesCount: 15,
    evaluatorsCount: 3,
    examinees: "/assets/files/مستندات.txt",
    evaluators: "/assets/files/مستندات.txt",
    province: "تهران",
    City: "تهران",
    location: "تهران مرکز",
    stauss: "پایان یافته",
    scheduleFile: "/assets/schedules/schedule_3.xlsx",
  },
  {
    id: 5,
    examTitle:
      "آزمون استخدامی نیروی انسانی سازمان زندانها و اقدامات تامینی و تربیتی کشور",
    organization: "سازمان زندانها و اقدامات تامینی و تربیتی کشور",
    job: "مامور گارد انتظامات زندانها",
    group: "گروه ب",
    examDate: "1404/01/10",
    examTime: "08:30",
    examEndDate: "1404/01/13", // 3 روز بعد
    examEndTime: "12:00",
    examineesCount: 35,
    evaluatorsCount: 7,
    examinees: "/assets/files/مستندات.txt",
    evaluators: "/assets/files/مستندات.txt",
    province: "مازندران",
    City: "تنکابن",
    location: "تنکابن",
    stauss: "سازماندهی",
    scheduleFile: "/assets/schedules/schedule_3.xlsx",
  },
  {
    id: 6,
    examTitle:
      "آزمون استخدام نيروی پيمانی مشاغل عملياتی آتش‌نشانی شهرداری اصفهان",
    organization: "سازمان شهرداری ها و دهیاری های کشور",
    job: "آتش‌نشان",
    group: "گروه ب",
    examDate: "1404/01/10",
    examTime: "08:30",
    examEndDate: "1404/01/12", // 2 روز بعد
    examEndTime: "15:00",
    examineesCount: 20,
    evaluatorsCount: 4,
    examinees: "/assets/files/مستندات.txt",
    evaluators: "/assets/files/مستندات.txt",
    province: "آذربایجان شرقی",
    City: "تبریز",
    location: "شهرداری تبریز",
    stauss: "پایان یافته",
    scheduleFile: "/assets/schedules/schedule_3.xlsx",
  },
  {
    id: 7,
    examTitle: "اولین آزمون استخدامی اختصاصی معلولان",
    organization: "سازمان بهزیستی کشور",
    job: "کارشناس اداری",
    group: "گروه ب",
    examDate: "1404/01/10",
    examTime: "08:30",
    examEndDate: "1404/01/13", // 3 روز بعد
    examEndTime: "14:00",
    examineesCount: 10,
    evaluatorsCount: 2,
    examinees: "/assets/files/مستندات.txt",
    evaluators: "/assets/files/مستندات.txt",
    province: "تهران",
    City: "دماوند",
    location: "رودهن",
    stauss: "پایان یافته",
    scheduleFile: "/assets/schedules/schedule_3.xlsx",
  },
  {
    id: 8,
    examTitle: "آزمون بکارگیری نیروی قرارداد کار معین شهرداری‌ ها",
    organization: "سازمان شهرداری ها و دهیاری های کشور",
    job: "حسابدار",
    group: "گروه الف",
    examDate: "1403/12/15",
    examTime: "08:00",
    examEndDate: "1403/12/17", // 2 روز بعد
    examEndTime: "12:00",
    examineesCount: 45,
    evaluatorsCount: 9,
    examinees: "/assets/files/مستندات.txt",
    evaluators: "/assets/files/مستندات.txt",
    province: "قزوین",
    City: "قزوین",
    location: "امام رضا (ع)، آلو متک، جابربن حیان، رشادت1، زینبیه",
    stauss: "سازماندهی",
    scheduleFile: "/assets/schedules/schedule_3.xlsx",
  },
  {
    id: 9,
    examTitle: "آزمون استخدامی شرکت فرودگاه‌ها و ناوبری هوایی ایران",
    organization: "وزارت راه و شهرسازی",
    job: "مهندس هوافضا",
    group: "گروه ب",
    examDate: "1403/12/20",
    examTime: "10:00",
    examEndDate: "1403/12/23", // 3 روز بعد
    examEndTime: "15:00",
    examineesCount: 12,
    evaluatorsCount: 3,
    examinees: "/assets/files/مستندات.txt",
    evaluators: "/assets/files/مستندات.txt",
    province: "تهران",
    City: "تهران",
    location: "فرودگاه امام خمینی",
    stauss: "در انتظار اجرا",
    scheduleFile: "/assets/schedules/schedule_3.xlsx",
  },
  {
    id: 10,
    examTitle: "آزمون استخدام نیروی انسانی وزارت امور خارجه جمهوری اسلامی",
    organization: "وزارت امور خارجه",
    job: "مترجم",
    group: "گروه ب",
    examDate: "1403/12/20",
    examTime: "10:00",
    examEndDate: "1403/12/22", // 2 روز بعد
    examEndTime: "14:00",
    examineesCount: 18,
    evaluatorsCount: 4,
    examinees: "/assets/files/مستندات.txt",
    evaluators: "/assets/files/مستندات.txt",
    province: "همدان",
    City: "اسدآباد",
    location: "مرکز خدمات جامع سلامت شهری و روستایی جنت آباد",
    stauss: "در انتظار اجرا",
    scheduleFile: "/assets/schedules/schedule_3.xlsx",
  },
];
