export const organizationData = [
  {
    id: "IR-01",
    name: "آذربایجان شرقی",
    centers: [
      {
        name: "حوزه ۱ تبریز",
        city: "تبریز",
        capacity: 500,
        occupied: 0,
        gender: "مرد",
        total: 700,
      },
      {
        name: "حوزه ۲ تبریز",
        city: "تبریز",
        capacity: 300,
        occupied: 0,
        gender: "زن",
        total: 500,
      },
      {
        name: "حوزه مراغه",
        city: "مراغه",
        capacity: 200,
        occupied: 0,
        gender: "مرد",
        total: 0,
      },
      {
        name: "حوزه میانه",
        city: "میانه",
        capacity: 250,
        occupied: 0,
        gender: "زن",
        total: 0,
      },
      {
        name: "حوزه اهر",
        city: "اهر",
        capacity: 150,
        occupied: 0,
        gender: "مرد",
        total: 0,
      },
    ],
  },
  {
    id: "IR-02",
    name: "آذربایجان غربی",
    centers: [
      {
        name: "حوزه ۱ ارومیه",
        city: "ارومیه",
        capacity: 600,
        occupied: 0,
        gender: "مرد",
        total: 500,
      },
      {
        name: "حوزه ۲ ارومیه",
        city: "ارومیه",
        capacity: 400,
        occupied: 0,
        gender: "زن",
        total: 400,
      },
      {
        name: "حوزه خوی",
        city: "خوی",
        capacity: 200,
        occupied: 0,
        gender: "مرد",
        total: 0,
      },
      {
        name: "حوزه مهاباد",
        city: "مهاباد",
        capacity: 250,
        occupied: 0,
        gender: "زن",
        total: 0,
      },
    ],
  },
  {
    id: "IR-03",
    name: "اردبیل",
    centers: [
      {
        name: "حوزه ۱ اردبیل",
        city: "اردبیل",
        capacity: 400,
        occupied: 0,
        gender: "مرد",
        total: 350,
      },
      {
        name: "حوزه ۲ اردبیل",
        city: "اردبیل",
        capacity: 300,
        occupied: 0,
        gender: "زن",
        total: 250,
      },
      {
        name: "حوزه مشگین شهر",
        city: "مشگین شهر",
        capacity: 200,
        occupied: 0,
        gender: "مرد",
        total: 0,
      },
    ],
  },
  {
    id: "IR-04",
    name: "اصفهان",
    centers: [
      {
        name: "حوزه ۱ اصفهان",
        city: "اصفهان",
        capacity: 800,
        occupied: 0,
        gender: "مرد",
        total: 1200,
      },
      {
        name: "حوزه ۲ اصفهان",
        city: "اصفهان",
        capacity: 600,
        occupied: 0,
        gender: "زن",
        total: 800,
      },
      {
        name: "حوزه کاشان",
        city: "کاشان",
        capacity: 300,
        occupied: 0,
        gender: "مرد",
        total: 0,
      },
      {
        name: "حوزه نجف آباد",
        city: "نجف آباد",
        capacity: 250,
        occupied: 0,
        gender: "زن",
        total: 0,
      },
    ],
  },
  {
    id: "IR-32",
    name: "البرز",
    centers: [
      {
        name: "حوزه ۱ کرج",
        city: "کرج",
        capacity: 700,
        occupied: 0,
        gender: "مرد",
        total: 450,
      },
      {
        name: "حوزه ۲ کرج",
        city: "کرج",
        capacity: 500,
        occupied: 0,
        gender: "زن",
        total: 350,
      },
      {
        name: "حوزه فردیس",
        city: "فردیس",
        capacity: 300,
        occupied: 0,
        gender: "مرد",
        total: 0,
      },
    ],
  },
  {
    id: "IR-05",
    name: "ایلام",
    centers: [
      {
        name: "حوزه ۱ ایلام",
        city: "ایلام",
        capacity: 300,
        occupied: 0,
        gender: "مرد",
        total: 180,
      },
      {
        name: "حوزه ۲ ایلام",
        city: "ایلام",
        capacity: 200,
        occupied: 0,
        gender: "زن",
        total: 120,
      },
      {
        name: "حوزه دهلران",
        city: "ده Zلران",
        capacity: 150,
        occupied: 0,
        gender: "مرد",
        total: 0,
      },
    ],
  },
  {
    id: "IR-06",
    name: "بوشهر",
    centers: [
      {
        name: "حوزه ۱ بوشهر",
        city: "بوشهر",
        capacity: 400,
        occupied: 0,
        gender: "مرد",
        total: 220,
      },
      {
        name: "حوزه ۲ بوشهر",
        city: "بوشهر",
        capacity: 300,
        occupied: 0,
        gender: "زن",
        total: 180,
      },
      {
        name: "حوزه کنگان",
        city: "کنگان",
        capacity: 200,
        occupied: 0,
        gender: "مرد",
        total: 0,
      },
    ],
  },
  {
    id: "IR-07",
    name: "تهران",
    centers: [
      {
        name: "حوزه ۱ تهران",
        city: "تهران",
        capacity: 1000,
        occupied: 0,
        gender: "مرد",
        total: 3000,
      },
      {
        name: "حوزه ۲ تهران",
        city: "تهران",
        capacity: 800,
        occupied: 0,
        gender: "زن",
        total: 2000,
      },
      {
        name: "حوزه شمیرانات",
        city: "شمیرانات",
        capacity: 500,
        occupied: 0,
        gender: "مرد",
        total: 0,
      },
      {
        name: "حوزه ری",
        city: "ری",
        capacity: 600,
        occupied: 0,
        gender: "زن",
        total: 0,
      },
      {
        name: "حوزه اسلامشهر",
        city: "اسلامشهر",
        capacity: 400,
        occupied: 0,
        gender: "مرد",
        total: 0,
      },
    ],
  },
  {
    id: "IR-08",
    name: "چهارمحال و بختیاری",
    centers: [
      {
        name: "حوزه ۱ شهرکرد",
        city: "شهرکرد",
        capacity: 300,
        occupied: 0,
        gender: "مرد",
        total: 200,
      },
      {
        name: "حوزه ۲ شهرکرد",
        city: "شهرکرد",
        capacity: 200,
        occupied: 0,
        gender: "زن",
        total: 150,
      },
      {
        name: "حوزه بروجن",
        city: "بروجن",
        capacity: 150,
        occupied: 0,
        gender: "مرد",
        total: 0,
      },
    ],
  },
  {
    id: "IR-29",
    name: "خراسان جنوبی",
    centers: [
      {
        name: "حوزه ۱ بیرجند",
        city: "بیرجند",
        capacity: 350,
        occupied: 0,
        gender: "مرد",
        total: 250,
      },
      {
        name: "حوزه ۲ بیرجند",
        city: "بیرجند",
        capacity: 250,
        occupied: 0,
        gender: "زن",
        total: 200,
      },
      {
        name: "حوزه قائن",
        city: "قائن",
        capacity: 200,
        occupied: 0,
        gender: "مرد",
        total: 0,
      },
    ],
  },
  {
    id: "IR-30",
    name: "خراسان رضوی",
    centers: [
      {
        name: "حوزه ۱ مشهد",
        city: "مشهد",
        capacity: 1000,
        occupied: 0,
        gender: "مرد",
        total: 1000,
      },
      {
        name: "حوزه ۲ مشهد",
        city: "مشهد",
        capacity: 800,
        occupied: 0,
        gender: "زن",
        total: 800,
      },
      {
        name: "حوزه نیشابور",
        city: "نیشابور",
        capacity: 400,
        occupied: 0,
        gender: "مرد",
        total: 0,
      },
      {
        name: "حوزه سبزوار",
        city: "سبزوار",
        capacity: 300,
        occupied: 0,
        gender: "زن",
        total: 0,
      },
    ],
  },
  {
    id: "IR-31",
    name: "خراسان شمالی",
    centers: [
      {
        name: "حوزه ۱ بجنورد",
        city: "بجنورد",
        capacity: 350,
        occupied: 0,
        gender: "مرد",
        total: 280,
      },
      {
        name: "حوزه ۲ بجنورد",
        city: "بجنورد",
        capacity: 250,
        occupied: 0,
        gender: "زن",
        total: 220,
      },
      {
        name: "حوزه شیروان",
        city: "شیروان",
        capacity: 200,
        occupied: 0,
        gender: "مرد",
        total: 0,
      },
    ],
  },
  {
    id: "IR-10",
    name: "خوزستان",
    centers: [
      {
        name: "حوزه ۱ اهواز",
        city: "اهواز",
        capacity: 800,
        occupied: 0,
        gender: "مرد",
        total: 850,
      },
      {
        name: "حوزه ۲ اهواز",
        city: "اهواز",
        capacity: 600,
        occupied: 0,
        gender: "زن",
        total: 650,
      },
      {
        name: "حوزه دزفول",
        city: "دزفول",
        capacity: 400,
        occupied: 0,
        gender: "مرد",
        total: 0,
      },
      {
        name: "حوزه آبادان",
        city: "آبادان",
        capacity: 300,
        occupied: 0,
        gender: "زن",
        total: 0,
      },
    ],
  },
  {
    id: "IR-11",
    name: "زنجان",
    centers: [
      {
        name: "حوزه ۱ زنجان",
        city: "زنجان",
        capacity: 400,
        occupied: 0,
        gender: "مرد",
        total: 350,
      },
      {
        name: "حوزه ۲ زنجان",
        city: "زنجان",
        capacity: 300,
        occupied: 0,
        gender: "زن",
        total: 250,
      },
      {
        name: "حوزه ابهر",
        city: "ابهر",
        capacity: 200,
        occupied: 0,
        gender: "مرد",
        total: 0,
      },
    ],
  },
  {
    id: "IR-12",
    name: "سمنان",
    centers: [
      {
        name: "حوزه ۱ سمنان",
        city: "سمنان",
        capacity: 300,
        occupied: 0,
        gender: "مرد",
        total: 220,
      },
      {
        name: "حوزه ۲ سمنان",
        city: "سمنان",
        capacity: 200,
        occupied: 0,
        gender: "زن",
        total: 180,
      },
      {
        name: "حوزه شاهرود",
        city: "شاهرود",
        capacity: 250,
        occupied: 0,
        gender: "مرد",
        total: 0,
      },
    ],
  },
  {
    id: "IR-13",
    name: "سیستان و بلوچستان",
    centers: [
      {
        name: "حوزه ۱ زاهدان",
        city: "زاهدان",
        capacity: 500,
        occupied: 0,
        gender: "مرد",
        total: 400,
      },
      {
        name: "حوزه ۲ زاهدان",
        city: "زاهدان",
        capacity: 400,
        occupied: 0,
        gender: "زن",
        total: 300,
      },
      {
        name: "حوزه چابهار",
        city: "چابهار",
        capacity: 300,
        occupied: 0,
        gender: "مرد",
        total: 0,
      },
    ],
  },
  {
    id: "IR-14",
    name: "فارس",
    centers: [
      {
        name: "حوزه ۱ شیراز",
        city: "شیراز",
        capacity: 900,
        occupied: 0,
        gender: "مرد",
        total: 950,
      },
      {
        name: "حوزه ۲ شیراز",
        city: "شیراز",
        capacity: 700,
        occupied: 0,
        gender: "زن",
        total: 750,
      },
      {
        name: "حوزه مرودشت",
        city: "مرودشت",
        capacity: 400,
        occupied: 0,
        gender: "مرد",
        total: 0,
      },
      {
        name: "حوزه جهرم",
        city: "جهرم",
        capacity: 300,
        occupied: 0,
        gender: "زن",
        total: 0,
      },
    ],
  },
  {
    id: "IR-28",
    name: "قزوین",
    centers: [
      {
        name: "حوزه ۱ قزوین",
        city: "قزوین",
        capacity: 400,
        occupied: 0,
        gender: "مرد",
        total: 320,
      },
      {
        name: "حوزه ۲ قزوین",
        city: "قزوین",
        capacity: 300,
        occupied: 0,
        gender: "زن",
        total: 230,
      },
      {
        name: "حوزه تاکستان",
        city: "تاکستان",
        capacity: 200,
        occupied: 0,
        gender: "مرد",
        total: 0,
      },
    ],
  },
  {
    id: "IR-26",
    name: "قم",
    centers: [
      {
        name: "حوزه ۱ قم",
        city: "قم",
        capacity: 600,
        occupied: 0,
        gender: "مرد",
        total: 380,
      },
      {
        name: "حوزه ۲ قم",
        city: "قم",
        capacity: 400,
        occupied: 0,
        gender: "زن",
        total: 270,
      },
      {
        name: "حوزه ۳ قم",
        city: "قم",
        capacity: 300,
        occupied: 0,
        gender: "مرد",
        total: 0,
      },
    ],
  },
  {
    id: "IR-16",
    name: "کردستان",
    centers: [
      {
        name: "حوزه ۱ سنندج",
        city: "سنندج",
        capacity: 400,
        occupied: 0,
        gender: "مرد",
        total: 280,
      },
      {
        name: "حوزه ۲ سنندج",
        city: "سنندج",
        capacity: 300,
        occupied: 0,
        gender: "زن",
        total: 220,
      },
      {
        name: "حوزه مریوان",
        city: "مریوان",
        capacity: 200,
        occupied: 0,
        gender: "مرد",
        total: 0,
      },
    ],
  },
  {
    id: "IR-15",
    name: "کرمان",
    centers: [
      {
        name: "حوزه ۱ کرمان",
        city: "کرمان",
        capacity: 600,
        occupied: 0,
        gender: "مرد",
        total: 500,
      },
      {
        name: "حوزه ۲ کرمان",
        city: "کرمان",
        capacity: 400,
        occupied: 0,
        gender: "زن",
        total: 400,
      },
      {
        name: "حوزه سیرجان",
        city: "سیرجان",
        capacity: 300,
        occupied: 0,
        gender: "مرد",
        total: 0,
      },
    ],
  },
  {
    id: "IR-17",
    name: "کرمانشاه",
    centers: [
      {
        name: "حوزه ۱ کرمانشاه",
        city: "کرمانشاه",
        capacity: 500,
        occupied: 0,
        gender: "مرد",
        total: 400,
      },
      {
        name: "حوزه ۲ کرمانشاه",
        city: "کرمانشاه",
        capacity: 400,
        occupied: 0,
        gender: "زن",
        total: 300,
      },
      {
        name: "حوزه اسلام آباد غرب",
        city: "اسلام آباد غرب",
        capacity: 250,
        occupied: 0,
        gender: "مرد",
        total: 0,
      },
    ],
  },
  {
    id: "IR-18",
    name: "کهگیلویه و بویراحمد",
    centers: [
      {
        name: "حوزه ۱ یاسوج",
        city: "یاسوج",
        capacity: 300,
        occupied: 0,
        gender: "مرد",
        total: 170,
      },
      {
        name: "حوزه ۲ یاسوج",
        city: "یاسوج",
        capacity: 200,
        occupied: 0,
        gender: "زن",
        total: 130,
      },
      {
        name: "حوزه گچساران",
        city: "گچساران",
        capacity: 150,
        occupied: 0,
        gender: "مرد",
        total: 0,
      },
    ],
  },
  {
    id: "IR-27",
    name: "گلستان",
    centers: [
      {
        name: "حوزه ۱ گرگان",
        city: "گرگان",
        capacity: 400,
        occupied: 0,
        gender: "مرد",
        total: 350,
      },
      {
        name: "حوزه ۲ گرگان",
        city: "گرگان",
        capacity: 300,
        occupied: 0,
        gender: "زن",
        total: 250,
      },
      {
        name: "حوزه گنبد کاووس",
        city: "گنبد کاووس",
        capacity: 250,
        occupied: 0,
        gender: "مرد",
        total: 0,
      },
    ],
  },
  {
    id: "IR-19",
    name: "گیلان",
    centers: [
      {
        name: "حوزه ۱ رشت",
        city: "رشت",
        capacity: 600,
        occupied: 0,
        gender: "مرد",
        total: 480,
      },
      {
        name: "حوزه ۲ رشت",
        city: "رشت",
        capacity: 400,
        occupied: 0,
        gender: "زن",
        total: 370,
      },
      {
        name: "حوزه لاهیجان",
        city: "لاهیجان",
        capacity: 300,
        occupied: 0,
        gender: "مرد",
        total: 0,
      },
    ],
  },
  {
    id: "IR-20",
    name: "لرستان",
    centers: [
      {
        name: "حوزه ۱ خرم آباد",
        city: "خرم آباد",
        capacity: 400,
        occupied: 0,
        gender: "مرد",
        total: 280,
      },
      {
        name: "حوزه ۲ خرم آباد",
        city: "خرم آباد",
        capacity: 300,
        occupied: 0,
        gender: "زن",
        total: 220,
      },
      {
        name: "حوزه بروجرد",
        city: "بروجرد",
        capacity: 250,
        occupied: 0,
        gender: "مرد",
        total: 0,
      },
    ],
  },
  {
    id: "IR-21",
    name: "مازندران",
    centers: [
      {
        name: "حوزه ۱ ساری",
        city: "ساری",
        capacity: 600,
        occupied: 0,
        gender: "مرد",
        total: 600,
      },
      {
        name: "حوزه ۲ ساری",
        city: "ساری",
        capacity: 400,
        occupied: 0,
        gender: "زن",
        total: 500,
      },
      {
        name: "حوزه بابل",
        city: "بابل",
        capacity: 300,
        occupied: 0,
        gender: "مرد",
        total: 0,
      },
      {
        name: "حوزه آمل",
        city: "آمل",
        capacity: 250,
        occupied: 0,
        gender: "زن",
        total: 0,
      },
    ],
  },
  {
    id: "IR-22",
    name: "مرکزی",
    centers: [
      {
        name: "حوزه ۱ اراک",
        city: "اراک",
        capacity: 400,
        occupied: 0,
        gender: "مرد",
        total: 350,
      },
      {
        name: "حوزه ۲ اراک",
        city: "اراک",
        capacity: 300,
        occupied: 0,
        gender: "زن",
        total: 250,
      },
      {
        name: "حوزه ساوه",
        city: "ساوه",
        capacity: 250,
        occupied: 0,
        gender: "مرد",
        total: 0,
      },
    ],
  },
  {
    id: "IR-23",
    name: "هرمزگان",
    centers: [
      {
        name: "حوزه ۱ بندرعباس",
        city: "بندرعباس",
        capacity: 500,
        occupied: 0,
        gender: "مرد",
        total: 250,
      },
      {
        name: "حوزه ۲ بندرعباس",
        city: "بندرعباس",
        capacity: 400,
        occupied: 0,
        gender: "زن",
        total: 200,
      },
      {
        name: "حوزه میناب",
        city: "میناب",
        capacity: 250,
        occupied: 0,
        gender: "مرد",
        total: 0,
      },
    ],
  },
  {
    id: "IR-24",
    name: "همدان",
    centers: [
      {
        name: "حوزه ۱ همدان",
        city: "همدان",
        capacity: 400,
        occupied: 0,
        gender: "مرد",
        total: 400,
      },
      {
        name: "حوزه ۲ همدان",
        city: "همدان",
        capacity: 300,
        occupied: 0,
        gender: "زن",
        total: 300,
      },
      {
        name: "حوزه ملایر",
        city: "ملایر",
        capacity: 250,
        occupied: 0,
        gender: "مرد",
        total: 0,
      },
    ],
  },
  {
    id: "IR-25",
    name: "یزد",
    centers: [
      {
        name: "حوزه ۱ یزد",
        city: "یزد",
        capacity: 400,
        occupied: 0,
        gender: "مرد",
        total: 280,
      },
      {
        name: "حوزه ۲ یزد",
        city: "یزد",
        capacity: 300,
        occupied: 0,
        gender: "زن",
        total: 220,
      },
      {
        name: "حوزه میبد",
        city: "میبد",
        capacity: 200,
        occupied: 0,
        gender: "مرد",
        total: 0,
      },
    ],
  },
];

export const volunteerData = [
  {
    id: "IR-01",
    name: "آذربایجان شرقی",
    candidates: [
      {
        gender: "مرد",
        total: 700,
        leftHanded: 50,
        needsAssistant: 30,
        unorganized: 700,
      },
      {
        gender: "زن",
        total: 500,
        leftHanded: 40,
        needsAssistant: 20,
        unorganized: 500,
      },
    ],
  },
  {
    id: "IR-02",
    name: "آذربایجان غربی",
    candidates: [
      {
        gender: "مرد",
        total: 500,
        leftHanded: 30,
        needsAssistant: 25,
        unorganized: 500,
      },
      {
        gender: "زن",
        total: 400,
        leftHanded: 20,
        needsAssistant: 15,
        unorganized: 400,
      },
    ],
  },
  {
    id: "IR-03",
    name: "اردبیل",
    candidates: [
      {
        gender: "مرد",
        total: 350,
        leftHanded: 20,
        needsAssistant: 10,
        unorganized: 350,
      },
      {
        gender: "زن",
        total: 250,
        leftHanded: 15,
        needsAssistant: 5,
        unorganized: 250,
      },
    ],
  },
  {
    id: "IR-04",
    name: "اصفهان",
    candidates: [
      {
        gender: "مرد",
        total: 1200,
        leftHanded: 80,
        needsAssistant: 50,
        unorganized: 1200,
      },
      {
        gender: "زن",
        total: 800,
        leftHanded: 60,
        needsAssistant: 40,
        unorganized: 800,
      },
    ],
  },
  {
    id: "IR-32",
    name: "البرز",
    candidates: [
      {
        gender: "مرد",
        total: 450,
        leftHanded: 30,
        needsAssistant: 20,
        unorganized: 450,
      },
      {
        gender: "زن",
        total: 350,
        leftHanded: 25,
        needsAssistant: 15,
        unorganized: 350,
      },
    ],
  },
  {
    id: "IR-05",
    name: "ایلام",
    candidates: [
      {
        gender: "مرد",
        total: 180,
        leftHanded: 10,
        needsAssistant: 5,
        unorganized: 180,
      },
      {
        gender: "زن",
        total: 120,
        leftHanded: 8,
        needsAssistant: 3,
        unorganized: 120,
      },
    ],
  },
  {
    id: "IR-06",
    name: "بوشهر",
    candidates: [
      {
        gender: "مرد",
        total: 220,
        leftHanded: 15,
        needsAssistant: 10,
        unorganized: 220,
      },
      {
        gender: "زن",
        total: 180,
        leftHanded: 10,
        needsAssistant: 5,
        unorganized: 180,
      },
    ],
  },
  {
    id: "IR-07",
    name: "تهران",
    candidates: [
      {
        gender: "مرد",
        total: 3000,
        leftHanded: 200,
        needsAssistant: 150,
        unorganized: 3000,
      },
      {
        gender: "زن",
        total: 2000,
        leftHanded: 150,
        needsAssistant: 100,
        unorganized: 2000,
      },
    ],
  },
  {
    id: "IR-08",
    name: "چهارمحال و بختیاری",
    candidates: [
      {
        gender: "مرد",
        total: 200,
        leftHanded: 12,
        needsAssistant: 8,
        unorganized: 200,
      },
      {
        gender: "زن",
        total: 150,
        leftHanded: 10,
        needsAssistant: 5,
        unorganized: 150,
      },
    ],
  },
  {
    id: "IR-29",
    name: "خراسان جنوبی",
    candidates: [
      {
        gender: "مرد",
        total: 250,
        leftHanded: 15,
        needsAssistant: 10,
        unorganized: 250,
      },
      {
        gender: "زن",
        total: 200,
        leftHanded: 12,
        needsAssistant: 8,
        unorganized: 200,
      },
    ],
  },
  {
    id: "IR-30",
    name: "خراسان رضوی",
    candidates: [
      {
        gender: "مرد",
        total: 1000,
        leftHanded: 70,
        needsAssistant: 40,
        unorganized: 1000,
      },
      {
        gender: "زن",
        total: 800,
        leftHanded: 50,
        needsAssistant: 30,
        unorganized: 800,
      },
    ],
  },
  {
    id: "IR-31",
    name: "خراسان شمالی",
    candidates: [
      {
        gender: "مرد",
        total: 280,
        leftHanded: 18,
        needsAssistant: 12,
        unorganized: 280,
      },
      {
        gender: "زن",
        total: 220,
        leftHanded: 15,
        needsAssistant: 8,
        unorganized: 220,
      },
    ],
  },
  {
    id: "IR-10",
    name: "خوزستان",
    candidates: [
      {
        gender: "مرد",
        total: 850,
        leftHanded: 60,
        needsAssistant: 35,
        unorganized: 850,
      },
      {
        gender: "زن",
        total: 650,
        leftHanded: 45,
        needsAssistant: 25,
        unorganized: 650,
      },
    ],
  },
  {
    id: "IR-11",
    name: "زنجان",
    candidates: [
      {
        gender: "مرد",
        total: 350,
        leftHanded: 20,
        needsAssistant: 15,
        unorganized: 350,
      },
      {
        gender: "زن",
        total: 250,
        leftHanded: 18,
        needsAssistant: 10,
        unorganized: 250,
      },
    ],
  },
  {
    id: "IR-12",
    name: "سمنان",
    candidates: [
      {
        gender: "مرد",
        total: 220,
        leftHanded: 15,
        needsAssistant: 8,
        unorganized: 220,
      },
      {
        gender: "زن",
        total: 180,
        leftHanded: 12,
        needsAssistant: 5,
        unorganized: 180,
      },
    ],
  },
  {
    id: "IR-13",
    name: "سیستان و بلوچستان",
    candidates: [
      {
        gender: "مرد",
        total: 400,
        leftHanded: 25,
        needsAssistant: 20,
        unorganized: 400,
      },
      {
        gender: "زن",
        total: 300,
        leftHanded: 20,
        needsAssistant: 15,
        unorganized: 300,
      },
    ],
  },
  {
    id: "IR-14",
    name: "فارس",
    candidates: [
      {
        gender: "مرد",
        total: 950,
        leftHanded: 60,
        needsAssistant: 40,
        unorganized: 950,
      },
      {
        gender: "زن",
        total: 750,
        leftHanded: 50,
        needsAssistant: 30,
        unorganized: 750,
      },
    ],
  },
  {
    id: "IR-28",
    name: "قزوین",
    candidates: [
      {
        gender: "مرد",
        total: 320,
        leftHanded: 20,
        needsAssistant: 12,
        unorganized: 320,
      },
      {
        gender: "زن",
        total: 230,
        leftHanded: 15,
        needsAssistant: 8,
        unorganized: 230,
      },
    ],
  },
  {
    id: "IR-26",
    name: "قم",
    candidates: [
      {
        gender: "مرد",
        total: 380,
        leftHanded: 25,
        needsAssistant: 15,
        unorganized: 380,
      },
      {
        gender: "زن",
        total: 270,
        leftHanded: 18,
        needsAssistant: 10,
        unorganized: 270,
      },
    ],
  },
  {
    id: "IR-16",
    name: "کردستان",
    candidates: [
      {
        gender: "مرد",
        total: 280,
        leftHanded: 18,
        needsAssistant: 10,
        unorganized: 280,
      },
      {
        gender: "زن",
        total: 220,
        leftHanded: 15,
        needsAssistant: 8,
        unorganized: 220,
      },
    ],
  },
  {
    id: "IR-15",
    name: "کرمان",
    candidates: [
      {
        gender: "مرد",
        total: 500,
        leftHanded: 30,
        needsAssistant: 20,
        unorganized: 500,
      },
      {
        gender: "زن",
        total: 400,
        leftHanded: 25,
        needsAssistant: 15,
        unorganized: 400,
      },
    ],
  },
  {
    id: "IR-17",
    name: "کرمانشاه",
    candidates: [
      {
        gender: "مرد",
        total: 400,
        leftHanded: 25,
        needsAssistant: 15,
        unorganized: 400,
      },
      {
        gender: "زن",
        total: 300,
        leftHanded: 20,
        needsAssistant: 10,
        unorganized: 300,
      },
    ],
  },
  {
    id: "IR-18",
    name: "کهگیلویه و بویراحمد",
    candidates: [
      {
        gender: "مرد",
        total: 170,
        leftHanded: 10,
        needsAssistant: 5,
        unorganized: 170,
      },
      {
        gender: "زن",
        total: 130,
        leftHanded: 8,
        needsAssistant: 3,
        unorganized: 130,
      },
    ],
  },
  {
    id: "IR-27",
    name: "گلستان",
    candidates: [
      {
        gender: "مرد",
        total: 350,
        leftHanded: 20,
        needsAssistant: 12,
        unorganized: 350,
      },
      {
        gender: "زن",
        total: 250,
        leftHanded: 15,
        needsAssistant: 8,
        unorganized: 250,
      },
    ],
  },
  {
    id: "IR-19",
    name: "گیلان",
    candidates: [
      {
        gender: "مرد",
        total: 480,
        leftHanded: 30,
        needsAssistant: 20,
        unorganized: 480,
      },
      {
        gender: "زن",
        total: 370,
        leftHanded: 25,
        needsAssistant: 15,
        unorganized: 370,
      },
    ],
  },
  {
    id: "IR-20",
    name: "لرستان",
    candidates: [
      {
        gender: "مرد",
        total: 280,
        leftHanded: 18,
        needsAssistant: 10,
        unorganized: 280,
      },
      {
        gender: "زن",
        total: 220,
        leftHanded: 15,
        needsAssistant: 8,
        unorganized: 220,
      },
    ],
  },
  {
    id: "IR-21",
    name: "مازندران",
    candidates: [
      {
        gender: "مرد",
        total: 600,
        leftHanded: 40,
        needsAssistant: 25,
        unorganized: 600,
      },
      {
        gender: "زن",
        total: 500,
        leftHanded: 35,
        needsAssistant: 20,
        unorganized: 500,
      },
    ],
  },
  {
    id: "IR-22",
    name: "مرکزی",
    candidates: [
      {
        gender: "مرد",
        total: 350,
        leftHanded: 20,
        needsAssistant: 12,
        unorganized: 350,
      },
      {
        gender: "زن",
        total: 250,
        leftHanded: 15,
        needsAssistant: 8,
        unorganized: 250,
      },
    ],
  },
  {
    id: "IR-23",
    name: "هرمزگان",
    candidates: [
      {
        gender: "مرد",
        total: 250,
        leftHanded: 15,
        needsAssistant: 10,
        unorganized: 250,
      },
      {
        gender: "زن",
        total: 200,
        leftHanded: 12,
        needsAssistant: 8,
        unorganized: 200,
      },
    ],
  },
  {
    id: "IR-24",
    name: "همدان",
    candidates: [
      {
        gender: "مرد",
        total: 400,
        leftHanded: 25,
        needsAssistant: 15,
        unorganized: 400,
      },
      {
        gender: "زن",
        total: 300,
        leftHanded: 20,
        needsAssistant: 10,
        unorganized: 300,
      },
    ],
  },
  {
    id: "IR-25",
    name: "یزد",
    candidates: [
      {
        gender: "مرد",
        total: 280,
        leftHanded: 18,
        needsAssistant: 10,
        unorganized: 280,
      },
      {
        gender: "زن",
        total: 220,
        leftHanded: 15,
        needsAssistant: 8,
        unorganized: 220,
      },
    ],
  },
];
