export const samplePermits = [
  {
    id: 1,
    number: "ج.ا.ا-2501",
    type: "request",
    status: "تأیید شده",
    organization: "شرکت تولید نیروی برق حرارتی",
    subOrganization: "شرکت تولید نیروی برق لوشان",
    employmentType: "رسمی",
    scoreRatio: "70/30",
    registrationDate: "1403/01/15",
    hiringCapacity: 120,
    capacityMultiplier: "3",
    confirmationDate: "1403/02/01",
    permitExpirationDate: "1404/03/23",
    quotaTable: [
      {
        jobTitle: "کارشناس امور مالی",
        province: "تهران",
        city: "تهران",
        location: "دفتر مرکزی",
        free: { female: "3", male: "3", both: "5" },
        quota3: { female: "5", male: "5", both: "5" },
        quota5: { female: "5", male: "5", both: "3" },
        quota25: { female: "3", male: "3", both: "5" },
      },
      {
        jobTitle: "کارشناس شبکه",
        province: "تهران",
        city: "ری",
        location: "تهران",
        free: { female: "5", male: "5", both: "5" },
        quota3: { female: "3", male: "3", both: "3" },
        quota5: { female: "6", male: "5", both: "5" },
        quota25: { female: "10", male: "10", both: "10" },
      },
    ],
    educationTable: [
      {
        job: "کارشناس امور مالی",
        degree: "کارشناسی",
        field: ["مدیریت مالی", "حسابداری"],
      },
      {
        job: "کارشناس امور مالی",
        degree: "کارشناسی ارشد",
        field: ["مدیریت مالی"],
      },
      {
        job: "کارشناس شبکه",
        degree: "کارشناسی",
        field: ["مهندسی فناوری اطلاعات", "مهندسی کامپیوتر"],
      },
    ],
    generalExamTable: [
      {
        job: "کارشناس امور مالی",
        title: "تسلط بر مبانی اسلامی - انقلابی",
        share: "10",
        resources: "ولایت فقیه، امام خمینی (ره)",
      },
      {
        job: "کارشناس امور مالی",
        title: "آشنایی با اسناد و قوانین بالادستی",
        share: "6",
        resources: "قانون اساسی، بیانیه گام دوم، برنامه هفتم توسعه",
      },
      {
        job: "کارشناس امور مالی",
        title: "زبان و ادبیات فارسی",
        share: "6",
        resources: "",
      },
      {
        job: "کارشناس امور مالی",
        title: "زبان انگلیسی عمومی",
        share: "6",
        resources: "",
      },
      {
        job: "کارشناس امور مالی",
        title: "هوش و توانمندی های ذهنی",
        share: "6",
        resources: "",
      },
      {
        job: "کارشناس امور مالی",
        title: "فناوری اطلاعات",
        share: "6",
        resources: "",
      },
      {
        job: "کارشناس شبکه",
        title: "تسلط بر مبانی اسلامی - انقلابی",
        share: "10",
        resources: "ولایت فقیه، امام خمینی (ره)",
      },
      {
        job: "کارشناس شبکه",
        title: "آشنایی با اسناد و قوانین بالادستی",
        share: "6",
        resources: "قانون اساسی، بیانیه گام دوم، برنامه هفتم توسعه",
      },
      {
        job: "کارشناس شبکه",
        title: "زبان و ادبیات فارسی",
        share: "6",
        resources: "",
      },
      {
        job: "کارشناس شبکه",
        title: "زبان انگلیسی عمومی",
        share: "6",
        resources: "",
      },
      {
        job: "کارشناس شبکه",
        title: "هوش و توانمندی های ذهنی",
        share: "6",
        resources: "",
      },
      {
        job: "کارشناس شبکه",
        title: "فناوری اطلاعات",
        share: "6",
        resources: "",
      },
    ],
    specializedExamTable: [
      {
        job: "کارشناس امور مالی",
        title: "اصول حسابداری",
        share: "12",
        resources: "",
      },
      {
        job: "کارشناس امور مالی",
        title: "حسابرسی",
        share: "12",
        resources: "",
      },
      {
        job: "کارشناس امور مالی",
        title: "حسابداری دولتی",
        share: "12",
        resources: "",
      },
      {
        job: "کارشناس امور مالی",
        title: "مدیریت مالی",
        share: "12",
        resources: "",
      },
      {
        job: "کارشناس امور مالی",
        title: "حسابداری مدیریت",
        share: "12",
        resources: "",
      },
      {
        job: "کارشناس شبکه",
        title: "پایگاه داده ها",
        share: "12",
        resources: "",
      },
      {
        job: "کارشناس شبکه",
        title: "امنیت شبکه",
        share: "12",
        resources: "",
      },
      {
        job: "کارشناس شبکه",
        title: "مدیریت پروژه های فناوری اطلاعات",
        share: "12",
        resources: "",
      },
      {
        job: "کارشناس شبکه",
        title: "شبکه های کامپیوتری",
        share: "12",
        resources: "",
      },
      {
        job: "کارشناس شبکه",
        title: "سیستم های عامل",
        share: "12",
        resources: "",
      },
    ],
    supplementaryEvaluationTable: [
      {
        job: "کارشناس امور مالی",
        domain: "عمومی",
        axis: "تعهد و تعلق سازماني",
        competency: "شخصیت شغلی",
        evaluationContent: "رفتار سازمانی",
        tool: "ابزارهاي فردي، گروهي و تعاملي",
        supplementaryShare: "40",
        totalShare: "40",
      },
      {
        job: "کارشناس امور مالی",
        domain: "اختصاصی",
        axis: "انعطاف پذيري و مسئوليت پذيري",
        competency: "نظم و انضباط",
        evaluationContent: "مسئولیت پذیری",
        tool: "آزمون عملي",
        supplementaryShare: "30",
        totalShare: "30",
      },
      {
        job: "کارشناس امور مالی",
        domain: "تخصصی",
        axis: "نظم پذيري",
        competency: "نظم و انضباط",
        evaluationContent: "مسئولیت پذیری",
        tool: "مصاحبه تخصصي",
        supplementaryShare: "30",
        totalShare: "30",
      },
      {
        job: "کارشناس شبکه",
        domain: "عمومی",
        axis: "هوش هيجاني",
        competency: "شخصیت شغلی",
        evaluationContent: "رفتار سازمانی",
        tool: "مصاحبه گروهي",
        supplementaryShare: "40",
        totalShare: "40",
      },
      {
        job: "کارشناس شبکه",
        domain: "اختصاصی",
        axis: "تعهد و تعلق سازماني",
        competency: "نظم و انضباط",
        evaluationContent: "مسئولیت پذیری",
        tool: "تحليل موردي",
        supplementaryShare: "30",
        totalShare: "30",
      },
      {
        job: "کارشناس شبکه",
        domain: "تخصصی",
        axis: "ويژگي هاي شخصيتي مرتبط با شغل",
        competency: "نظم و انضباط",
        evaluationContent: "مسئولیت پذیری",
        tool: "بررسي ميدانی مصاحبه تخصصي",
        supplementaryShare: "30",
        totalShare: "30",
      },
    ],
    permitNumber: "ج.ا.ا-2501",
    requestLetter: "",
  },
  {
    id: 2,
    number: "ج.ا.ا-3251",
    type: "request",
    status: "تأیید شده",
    organization: "سازمان بهزیستی کشور",
    subOrganization: "معاونت پیشگیری از معلولیت‌ها",
    employmentType: "رسمی",
    scoreRatio: "70/30",
    registrationDate: "1403/01/15",
    hiringCapacity: 120,
    capacityMultiplier: "3",
    confirmationDate: "1403/02/01",
    permitExpirationDate: "1404/04/23",

    quotaTable: [
      {
        jobTitle: "كارشناس امور توانبخشي",
        province: "البرز",
        city: "کرج",
        location: "مدیریت بهزیستی شهرستان کرج",
        free: { female: "3", male: "3", both: "5" },
        quota3: { female: "5", male: "5", both: "5" },
        quota5: { female: "5", male: "5", both: "3" },
        quota25: { female: "3", male: "3", both: "5" },
      },
      {
        jobTitle: "کارشناس امور بهزیستی",
        province: "اردبیل",
        city: "اردبیل",
        location: "مرکز اورژانس اجتماعی - اردبیل",
        free: { female: "5", male: "5", both: "5" },
        quota3: { female: "3", male: "3", both: "3" },
        quota5: { female: "6", male: "5", both: "5" },
        quota25: { female: "10", male: "10", both: "10" },
      },
    ],
    educationTable: [
      {
        job: "كارشناس امور توانبخشي",
        degree: "کارشناسی",
        field: [
          "توانبخشی حرفه‌ای",
          "اصول و مبانی توانبخشی",
          "توانبخشی اجتماعی",
          "قانون حمایت از معلولان",
          "اصول طبقه‌بندی بین‌المللی عملکرد، ناتوانی و سلامت",
        ],
      },
      {
        job: "كارشناس امور توانبخشي",
        degree: "کارشناسی ارشد",
        field: [
          "روان‌شناسی رشد",
          "بهداشت جامعه",
          "مبانی مدیریت",
          "اصول و مبانی توانبخشی",
        ],
      },
      {
        job: "کارشناس امور بهزیستی",
        degree: "کارشناسی",
        field: ["نظریه های جامعه شناسی", "نظریه های مددکاری", "خانواده درمانی"],
      },
    ],
    generalExamTable: [
      {
        job: "كارشناس امور توانبخشي",
        title: "معارف اسلامی",
        share: "5.7",
        resources: "ولایت فقیه، امام خمینی (ره)",
      },
      {
        job: "كارشناس امور توانبخشي",
        title: "زبان و ادبیات فارسی",
        share: "5.7",
        resources: "",
      },
      {
        job: "كارشناس امور توانبخشي",
        title: "آشنایی با قوانین و مقررات اداری",
        share: "5.7",
        resources: "",
      },
      {
        job: "كارشناس امور توانبخشي",
        title: "معلومات عمومی",
        share: "5.7",
        resources: "",
      },
      {
        job: "كارشناس امور توانبخشي",
        title: "زبان انگلیسی عمومی",
        share: "5.7",
        resources: "",
      },
      {
        job: "كارشناس امور توانبخشي",
        title: "هوش و توانمندی‌های ذهنی",
        share: "5.7",
        resources: "",
      },
      {
        job: "كارشناس امور توانبخشي",
        title: "فناوری اطلاعات",
        share: "5.7",
        resources: "",
      },
      {
        job: "کارشناس امور بهزیستی",
        title: "معارف اسلامی",
        share: "5.7",
        resources: "ولایت فقیه، امام خمینی (ره)",
      },
      {
        job: "کارشناس امور بهزیستی",
        title: "زبان و ادبیات فارسی",
        share: "5.7",
        resources: "قانون اساسی، بیانیه گام دوم، برنامه هفتم توسعه",
      },
      {
        job: "کارشناس امور بهزیستی",
        title: "آشنایی با قوانین و مقررات اداری",
        share: "5.7",
        resources: "",
      },
      {
        job: "کارشناس امور بهزیستی",
        title: "معلومات عمومی",
        share: "5.7",
        resources: "",
      },
      {
        job: "کارشناس امور بهزیستی",
        title: "زبان انگلیسی عمومی",
        share: "5.7",
        resources: "",
      },
      {
        job: "کارشناس امور بهزیستی",
        title: "هوش و توانمندی‌های ذهنی",
        share: "5.7",
        resources: "",
      },
      {
        job: "کارشناس امور بهزیستی",
        title: "فناوری اطلاعات",
        share: "5.7",
        resources: "",
      },
    ],
    specializedExamTable: [
      {
        job: "كارشناس امور توانبخشي",
        title: "بيماری‌های داخلی، عفونی",
        share: "15",
        resources: "",
      },
      {
        job: "كارشناس امور توانبخشي",
        title: "بیماری های کودکان",
        share: "15",
        resources: "",
      },
      {
        job: "كارشناس امور توانبخشي",
        title: "اصول و مبانی توانبخشی",
        share: "15",
        resources: "",
      },
      {
        job: "كارشناس امور توانبخشي",
        title: "اصول و مبانی توانبخشی",
        share: "15",
        resources: "",
      },
      {
        job: "كارشناس امور توانبخشي",
        title: "روانشناسی سلامت",
        share: "15",
        resources: "",
      },
      {
        job: "کارشناس امور بهزیستی",
        title: "اصول و مبانی توانبخشی",
        share: "15",
        resources: "",
      },
      {
        job: "کارشناس امور بهزیستی",
        title: "روانشناسی (رشد، سلامت، کودکان استثنائی)",
        share: "15",
        resources: "",
      },
      {
        job: "کارشناس امور بهزیستی",
        title: "روانشناسی افراد دارای معلولیت",
        share: "10",
        resources: "",
      },
      {
        job: "کارشناس امور بهزیستی",
        title: "قانون حمایت از حقوق معلولان",
        share: "10",
        resources: "",
      },
      {
        job: "کارشناس امور بهزیستی",
        title: "توانبخشی اجتماعی",
        share: "12",
        resources: "",
      },
    ],
    supplementaryEvaluationTable: [
      {
        job: "كارشناس امور توانبخشي",
        domain: "عمومی",
        axis: "تعهد و تعلق سازماني",
        competency: "شخصیت شغلی",
        evaluationContent: "رفتار سازمانی",
        tool: "ابزارهاي فردي، گروهي و تعاملي",
        supplementaryShare: "40",
        totalShare: "40",
      },
      {
        job: "كارشناس امور توانبخشي",
        domain: "اختصاصی",
        axis: "انعطاف پذيري و مسئوليت پذيري",
        competency: "نظم و انضباط",
        evaluationContent: "مسئولیت پذیری",
        tool: "آزمون عملي",
        supplementaryShare: "30",
        totalShare: "30",
      },
      {
        job: "كارشناس امور توانبخشي",
        domain: "تخصصی",
        axis: "نظم پذيري",
        competency: "نظم و انضباط",
        evaluationContent: "مسئولیت پذیری",
        tool: "مصاحبه تخصصي",
        supplementaryShare: "30",
        totalShare: "30",
      },
      {
        job: "کارشناس امور بهزیستی",
        domain: "عمومی",
        axis: "هوش هيجاني",
        competency: "شخصیت شغلی",
        evaluationContent: "رفتار سازمانی",
        tool: "مصاحبه گروهي",
        supplementaryShare: "40",
        totalShare: "40",
      },
      {
        job: "کارشناس امور بهزیستی",
        domain: "اختصاصی",
        axis: "تعهد و تعلق سازماني",
        competency: "نظم و انضباط",
        evaluationContent: "مسئولیت پذیری",
        tool: "تحليل موردي",
        supplementaryShare: "30",
        totalShare: "30",
      },
      {
        job: "کارشناس امور بهزیستی",
        domain: "تخصصی",
        axis: "ويژگي هاي شخصيتي مرتبط با شغل",
        competency: "نظم و انضباط",
        evaluationContent: "مسئولیت پذیری",
        tool: "بررسي ميدانی مصاحبه تخصصي",
        supplementaryShare: "30",
        totalShare: "30",
      },
    ],
    permitNumber: "ج.ا.ا-3251",
    requestLetter: "",
  },
  // {
  //   id: 3,
  //   number: "ج.ا.ا-1541",
  //   type: "request",
  //   status: "در انتظار",
  //   organization: "وزارت نیرو",
  //   subOrganization: "شرکت توانیر",
  //   employmentType: "پیمانی",
  //   scoreRatio: "40/60",
  //   registrationDate: "1403/01/15",
  //   hiringCapacity: 120,
  //   capacityMultiplier: "3",
  //   confirmationDate: "1403/08/21",
  //   permitExpirationDate: "1404/03/23",

  //   quotaTable: [
  //     {
  //       jobTitle: "كارشناس امور توانبخشي",
  //       province: "البرز",
  //       city: "کرج",
  //       location: "مدیریت بهزیستی شهرستان کرج",
  //       free: { female: "3", male: "3", both: "5" },
  //       quota3: { female: "5", male: "5", both: "5" },
  //       quota5: { female: "5", male: "5", both: "3" },
  //       quota25: { female: "3", male: "3", both: "5" },
  //     },
  //     {
  //       jobTitle: "کارشناس امور بهزیستی",
  //       province: "اردبیل",
  //       city: "اردبیل",
  //       location: "مرکز اورژانس اجتماعی - اردبیل",
  //       free: { female: "5", male: "5", both: "5" },
  //       quota3: { female: "3", male: "3", both: "3" },
  //       quota5: { female: "6", male: "5", both: "5" },
  //       quota25: { female: "10", male: "10", both: "10" },
  //     },
  //   ],
  //   educationTable: [
  //     {
  //       job: "كارشناس امور توانبخشي",
  //       degree: "کارشناسی",
  //       field: [
  //         "توانبخشی حرفه‌ای",
  //         "اصول و مبانی توانبخشی",
  //         "توانبخشی اجتماعی",
  //         "قانون حمایت از معلولان",
  //         "اصول طبقه‌بندی بین‌المللی عملکرد، ناتوانی و سلامت",
  //       ],
  //     },
  //     {
  //       job: "كارشناس امور توانبخشي",
  //       degree: "کارشناسی ارشد",
  //       field: [
  //         "روان‌شناسی رشد",
  //         "بهداشت جامعه",
  //         "مبانی مدیریت",
  //         "اصول و مبانی توانبخشی",
  //       ],
  //     },
  //     {
  //       job: "کارشناس امور بهزیستی",
  //       degree: "کارشناسی",
  //       field: ["نظریه های جامعه شناسی", "نظریه های مددکاری", "خانواده درمانی"],
  //     },
  //   ],
  //   generalExamTable: [
  //     {
  //       job: "كارشناس امور توانبخشي",
  //       title: "معارف اسلامی",
  //       share: "5.7",
  //       resources: "ولایت فقیه، امام خمینی (ره)",
  //     },
  //     {
  //       job: "كارشناس امور توانبخشي",
  //       title: "زبان و ادبیات فارسی",
  //       share: "5.7",
  //       resources: "",
  //     },
  //     {
  //       job: "كارشناس امور توانبخشي",
  //       title: "آشنایی با قوانین و مقررات اداری",
  //       share: "5.7",
  //       resources: "",
  //     },
  //     {
  //       job: "كارشناس امور توانبخشي",
  //       title: "معلومات عمومی",
  //       share: "5.7",
  //       resources: "",
  //     },
  //     {
  //       job: "كارشناس امور توانبخشي",
  //       title: "زبان انگلیسی عمومی",
  //       share: "5.7",
  //       resources: "",
  //     },
  //     {
  //       job: "كارشناس امور توانبخشي",
  //       title: "هوش و توانمندی‌های ذهنی",
  //       share: "5.7",
  //       resources: "",
  //     },
  //     {
  //       job: "كارشناس امور توانبخشي",
  //       title: "فناوری اطلاعات",
  //       share: "5.7",
  //       resources: "",
  //     },
  //     {
  //       job: "کارشناس امور بهزیستی",
  //       title: "معارف اسلامی",
  //       share: "5.7",
  //       resources: "ولایت فقیه، امام خمینی (ره)",
  //     },
  //     {
  //       job: "کارشناس امور بهزیستی",
  //       title: "زبان و ادبیات فارسی",
  //       share: "5.7",
  //       resources: "قانون اساسی، بیانیه گام دوم، برنامه هفتم توسعه",
  //     },
  //     {
  //       job: "کارشناس امور بهزیستی",
  //       title: "آشنایی با قوانین و مقررات اداری",
  //       share: "5.7",
  //       resources: "",
  //     },
  //     {
  //       job: "کارشناس امور بهزیستی",
  //       title: "معلومات عمومی",
  //       share: "5.7",
  //       resources: "",
  //     },
  //     {
  //       job: "کارشناس امور بهزیستی",
  //       title: "زبان انگلیسی عمومی",
  //       share: "5.7",
  //       resources: "",
  //     },
  //     {
  //       job: "کارشناس امور بهزیستی",
  //       title: "هوش و توانمندی‌های ذهنی",
  //       share: "5.7",
  //       resources: "",
  //     },
  //     {
  //       job: "کارشناس امور بهزیستی",
  //       title: "فناوری اطلاعات",
  //       share: "5.7",
  //       resources: "",
  //     },
  //   ],
  //   specializedExamTable: [
  //     {
  //       job: "كارشناس امور توانبخشي",
  //       title: "بيماری‌های داخلی، عفونی",
  //       share: "15",
  //       resources: "",
  //     },
  //     {
  //       job: "كارشناس امور توانبخشي",
  //       title: "بیماری های کودکان",
  //       share: "15",
  //       resources: "",
  //     },
  //     {
  //       job: "كارشناس امور توانبخشي",
  //       title: "اصول و مبانی توانبخشی",
  //       share: "15",
  //       resources: "",
  //     },
  //     {
  //       job: "كارشناس امور توانبخشي",
  //       title: "اصول و مبانی توانبخشی",
  //       share: "15",
  //       resources: "",
  //     },
  //     {
  //       job: "كارشناس امور توانبخشي",
  //       title: "روانشناسی سلامت",
  //       share: "15",
  //       resources: "",
  //     },
  //     {
  //       job: "کارشناس امور بهزیستی",
  //       title: "اصول و مبانی توانبخشی",
  //       share: "15",
  //       resources: "",
  //     },
  //     {
  //       job: "کارشناس امور بهزیستی",
  //       title: "روانشناسی (رشد، سلامت، کودکان استثنائی)",
  //       share: "15",
  //       resources: "",
  //     },
  //     {
  //       job: "کارشناس امور بهزیستی",
  //       title: "روانشناسی افراد دارای معلولیت",
  //       share: "10",
  //       resources: "",
  //     },
  //     {
  //       job: "کارشناس امور بهزیستی",
  //       title: "قانون حمایت از حقوق معلولان",
  //       share: "10",
  //       resources: "",
  //     },
  //     {
  //       job: "کارشناس امور بهزیستی",
  //       title: "توانبخشی اجتماعی",
  //       share: "12",
  //       resources: "",
  //     },
  //   ],
  //   supplementaryEvaluationTable: [
  //     {
  //       job: "كارشناس امور توانبخشي",
  //       domain: "عمومی",
  //       axis: "تعهد و تعلق سازماني",
  //       competency: "شخصیت شغلی",
  //       evaluationContent: "رفتار سازمانی",
  //       tool: "ابزارهاي فردي، گروهي و تعاملي",
  //       supplementaryShare: "40",
  //       totalShare: "40",
  //     },
  //     {
  //       job: "كارشناس امور توانبخشي",
  //       domain: "اختصاصی",
  //       axis: "انعطاف پذيري و مسئوليت پذيري",
  //       competency: "نظم و انضباط",
  //       evaluationContent: "مسئولیت پذیری",
  //       tool: "آزمون عملي",
  //       supplementaryShare: "30",
  //       totalShare: "30",
  //     },
  //     {
  //       job: "كارشناس امور توانبخشي",
  //       domain: "تخصصی",
  //       axis: "نظم پذيري",
  //       competency: "نظم و انضباط",
  //       evaluationContent: "مسئولیت پذیری",
  //       tool: "مصاحبه تخصصي",
  //       supplementaryShare: "30",
  //       totalShare: "30",
  //     },
  //     {
  //       job: "کارشناس امور بهزیستی",
  //       domain: "عمومی",
  //       axis: "هوش هيجاني",
  //       competency: "شخصیت شغلی",
  //       evaluationContent: "رفتار سازمانی",
  //       tool: "مصاحبه گروهي",
  //       supplementaryShare: "40",
  //       totalShare: "40",
  //     },
  //     {
  //       job: "کارشناس امور بهزیستی",
  //       domain: "اختصاصی",
  //       axis: "تعهد و تعلق سازماني",
  //       competency: "نظم و انضباط",
  //       evaluationContent: "مسئولیت پذیری",
  //       tool: "تحليل موردي",
  //       supplementaryShare: "30",
  //       totalShare: "30",
  //     },
  //     {
  //       job: "کارشناس امور بهزیستی",
  //       domain: "تخصصی",
  //       axis: "ويژگي هاي شخصيتي مرتبط با شغل",
  //       competency: "نظم و انضباط",
  //       evaluationContent: "مسئولیت پذیری",
  //       tool: "بررسي ميدانی مصاحبه تخصصي",
  //       supplementaryShare: "30",
  //       totalShare: "30",
  //     },
  //   ],
  //   permitNumber: "ج.ا.ا-1821",
  //   requestLetter: "",
  // },
];
