import { FaDatabase } from "react-icons/fa6";
import { IoIosMan } from "react-icons/io";
import { FaUserGraduate } from "react-icons/fa";
import { PiBooksBold } from "react-icons/pi";
import { PiMedalMilitaryBold } from "react-icons/pi";
import { BsFillClipboard2CheckFill } from "react-icons/bs";

// استپ‌ها
export const steps = [
  { name: "درخواست شرایط", description: "مشاهده جزئیات درخواست" },
  {
    name: "اطلاعات پایه",
    description: "اطلاعات پایه جهت تعریف کلیات درخواست",
  },
  {
    name: "احراز جنسیت-سهمیه",
    description: "احراز شرایط جنسیت-سهمیه به ازای هر شغل محل",
  },
  {
    name: "احراز مقطع-رشته",
    description: "احراز شرایط مقطع-رشته به ازای هر شغل محل",
  },
  {
    name: "مواد آزمون کتبی",
    description: "موارد و مراحلی که نیاز است برای آزمون کتبی طی شود",
  },
  {
    name: "مواد ارزیابی تکمیلی",
    description: "موارد و مراحلی که نیاز است برای ارزیابی تکمیلی طی شود",
  },
  {
    name: "ثبت نهایی",
    description: "ثبت نهایی درخواست",
  },
];

// آیکون‌ها
export const stepIcons = [
  <BsFillClipboard2CheckFill />,
  <FaDatabase />,
  <IoIosMan />,
  <FaUserGraduate />,
  <PiBooksBold />,
  <PiMedalMilitaryBold />,
  <BsFillClipboard2CheckFill />,
];

// گزینه‌های شغل
export const jobOptions = [
  { value: "آینده پژوه", label: "آینده پژوه" },
  { value: "کارشناس امور بهزیستی", label: "کارشناس امور بهزیستی" },
  {
    value: "استاد دانشگاه (در دانشگاه‌های دولتی)",
    label: "استاد دانشگاه (در دانشگاه‌های دولتی)",
  },
  { value: "برنامه نویس", label: "برنامه نویس" },
  { value: "حسابدار دولتی", label: "حسابدار دولتی" },
  {
    value: "داروساز در داروخانه‌های دولتی",
    label: "داروساز در داروخانه‌های دولتی",
  },
  { value: "كارشناس امور بهزيستي", label: "كارشناس امور بهزيستي" },
  { value: "كارشناس امور توانبخشي", label: "كارشناس امور توانبخشي" },
  { value: "مامور اجرایی محیط زیست", label: "مامور اجرایی محیط زیست" },
  { value: "مربی فنی و حرفه‌ای", label: "مربی فنی و حرفه‌ای" },
  { value: "مسئول دبیرخانه", label: "مسئول دبیرخانه" },
  {
    value: "معاونت پیشگیری از معلولیت‌ها",
    label: "معاونت پیشگیری از معلولیت‌ها",
  },
  { value: "کارشناس امور مالی", label: "کارشناس امور مالی" },
  { value: "کارشناس شبکه", label: "کارشناس شبکه" },
  { value: "معلم (در آموزش و پرورش)", label: "معلم (در آموزش و پرورش)" },
  {
    value: "مهندس برق (در شرکت توانیر یا وزارت نیرو)",
    label: "مهندس برق (در شرکت توانیر یا وزارت نیرو)",
  },
  {
    value: "مهندس عمران (در شهرداری‌ها و وزارت راه و شهرسازی)",
    label: "مهندس عمران (در شهرداری‌ها و وزارت راه و شهرسازی)",
  },
  {
    value: "مهندس مکانیک (در سازمان‌های صنعتی دولتی)",
    label: "مهندس مکانیک (در سازمان‌های صنعتی دولتی)",
  },
  {
    value: "مهندس کشاورزی (در جهاد کشاورزی)",
    label: "مهندس کشاورزی (در جهاد کشاورزی)",
  },
  { value: "نگهبان", label: "نگهبان" },
  {
    value: "پرستار در بیمارستان‌های دولتی",
    label: "پرستار در بیمارستان‌های دولتی",
  },
  {
    value: "پزشک عمومی در مراکز بهداشت دولتی",
    label: "پزشک عمومی در مراکز بهداشت دولتی",
  },
  {
    value: "پژوهشگر در مراکز تحقیقاتی دولتی",
    label: "پژوهشگر در مراکز تحقیقاتی دولتی",
  },
  {
    value: "کارشناس آزمایشگاه محیط زیست",
    label: "کارشناس آزمایشگاه محیط زیست",
  },
  {
    value: "کارشناس آموزش و ترویج حفاظت محیط زیست",
    label: "کارشناس آموزش و ترویج حفاظت محیط زیست",
  },
  {
    value: "کارشناس ارزیاب توان اکولوژیک سرزمین",
    label: "کارشناس ارزیاب توان اکولوژیک سرزمین",
  },
  { value: "کارشناس امور اداری", label: "کارشناس امور اداری" },
  { value: "کارشناس امور مالیاتی", label: "کارشناس امور مالیاتی" },
  {
    value: "کارشناس بررسی آلودگی آب و خاک",
    label: "کارشناس بررسی آلودگی آب و خاک",
  },
  { value: "کارشناس برنامه‌ریزی آموزشی", label: "کارشناس برنامه‌ریزی آموزشی" },
  { value: "کارشناس بهداشت محیط", label: "کارشناس بهداشت محیط" },
  { value: "کارشناس بودجه و مالی", label: "کارشناس بودجه و مالی" },
  {
    value: "کارشناس تغذیه در مراکز درمانی دولتی",
    label: "کارشناس تغذیه در مراکز درمانی دولتی",
  },
  {
    value: "کارشناس حیات وحش و بیماریهای حیات وحش",
    label: "کارشناس حیات وحش و بیماریهای حیات وحش",
  },
  { value: "کارشناس زیستگاههای آبی", label: "کارشناس زیستگاههای آبی" },
  { value: "کارشناس زیستگاههای خشکی", label: "کارشناس زیستگاههای خشکی" },
  {
    value: "کارشناس فناوری اطلاعات و شبکه",
    label: "کارشناس فناوری اطلاعات و شبکه",
  },
  { value: "کارشناس منابع انسانی", label: "کارشناس منابع انسانی" },
  { value: "کارشناس پایش محیط زیست", label: "کارشناس پایش محیط زیست" },
];

// گزینه‌های حیطه
export const domainOptions = [
  { value: "فنی", label: "فنی" },
  { value: "مدیریتی", label: "مدیریتی" },
  { value: "ارتباطی", label: "ارتباطی" },
  { value: "آموزشی", label: "آموزشی" },
  { value: "تحقیقی", label: "تحقیقی" },
  { value: "بازاریابی", label: "بازاریابی" },
  { value: "تحلیل و مشاوره", label: "تحلیل و مشاوره" },
];

// گزینه‌های استان
export const provinceOptions = [
  { value: "آذربایجان شرقی", label: "آذربایجان شرقی" },
  { value: "آذربایجان غربی", label: "آذربایجان غربی" },
  { value: "اردبیل", label: "اردبیل" },
  { value: "اصفهان", label: "اصفهان" },
  { value: "البرز", label: "البرز" },
  { value: "ایلام", label: "ایلام" },
  { value: "بوشهر", label: "بوشهر" },
  { value: "تهران", label: "تهران" },
  { value: "چهارمحال و بختیاری", label: "چهارمحال و بختیاری" },
  { value: "خراسان جنوبی", label: "خراسان جنوبی" },
  { value: "خراسان رضوی", label: "خراسان رضوی" },
  { value: "خراسان شمالی", label: "خراسان شمالی" },
  { value: "خوزستان", label: "خوزستان" },
  { value: "زنجان", label: "زنجان" },
  { value: "سمنان", label: "سمنان" },
  { value: "سیستان و بلوچستان", label: "سیستان و بلوچستان" },
  { value: "فارس", label: "فارس" },
  { value: "قزوین", label: "قزوین" },
  { value: "قم", label: "قم" },
  { value: "کردستان", label: "کردستان" },
  { value: "کرمان", label: "کرمان" },
  { value: "کرمانشاه", label: "کرمانشاه" },
  { value: "کهگیلویه و بویراحمد", label: "کهگیلویه و بویراحمد" },
  { value: "گلستان", label: "گلستان" },
  { value: "گیلان", label: "گیلان" },
  { value: "لرستان", label: "لرستان" },
  { value: "مازندران", label: "مازندران" },
  { value: "مرکزی", label: "مرکزی" },
  { value: "هرمزگان", label: "هرمزگان" },
  { value: "همدان", label: "همدان" },
  { value: "یزد", label: "یزد" },
];

// گزینه‌های شهر
export const cityOptions = {
  تهران: [
    { value: "تهران", label: "تهران" },
    { value: "شمیرانات", label: "شمیرانات" },
    { value: "اسلامشهر", label: "اسلامشهر" },
    { value: "بهارستان", label: "بهارستان" },
    { value: "پاکدشت", label: "پاکدشت" },
    { value: "ری", label: "ری" },
    { value: "رباط‌کریم", label: "رباط‌کریم" },
    { value: "شهریار", label: "شهریار" },
    { value: "قدس", label: "قدس" },
    { value: "قرچک", label: "قرچک" },
    { value: "ورامین", label: "ورامین" },
    { value: "دماوند", label: "دماوند" },
    { value: "فیروزکوه", label: "فیروزکوه" },
    { value: "ملارد", label: "ملارد" },
  ],
  مرکزی: [
    { value: "اراک", label: "اراک" },
    { value: "ساوه", label: "ساوه" },
    { value: "خمین", label: "خمین" },
    { value: "دلیجان", label: "دلیجان" },
    { value: "محلات", label: "محلات" },
    { value: "تفرش", label: "تفرش" },
    { value: "آشتیان", label: "آشتیان" },
    { value: "شازند", label: "شازند" },
    { value: "زرندیه", label: "زرندیه" },
    { value: "کمیجان", label: "کمیجان" },
    { value: "فراهان", label: "فراهان" },
    { value: "خنداب", label: "خنداب" },
  ],
  اصفهان: [
    { value: "آران و بیدگل", label: "آران و بیدگل" },
    { value: "اردستان", label: "اردستان" },
    { value: "اصفهان", label: "اصفهان" },
    { value: "برخوار", label: "برخوار" },
    { value: "بوئین و میاندشت", label: "بوئین و میاندشت" },
    { value: "تیران و کرون", label: "تیران و کرون" },
    { value: "چادگان", label: "چادگان" },
    { value: "خمینی‌شهر", label: "خمینی‌شهر" },
    { value: "خوانسار", label: "خوانسار" },
    { value: "خور و بیابانک", label: "خور و بیابانک" },
    { value: "دهاقان", label: "دهاقان" },
    { value: "سمیرم", label: "سمیرم" },
    { value: "شاهین‌شهر و میمه", label: "شاهین‌شهر و میمه" },
    { value: "شهرضا", label: "شهرضا" },
    { value: "فریدن", label: "فریدن" },
    { value: "فریدون‌شهر", label: "فریدون‌شهر" },
    { value: "فلاورجان", label: "فلاورجان" },
    { value: "کاشان", label: "کاشان" },
    { value: "گلپایگان", label: "گلپایگان" },
    { value: "لنجان", label: "لنجان" },
    { value: "مبارکه", label: "مبارکه" },
    { value: "نائین", label: "نائین" },
    { value: "نجف‌آباد", label: "نجف‌آباد" },
    { value: "نطنز", label: "نطنز" },
  ],
  ایلام: [
    { value: "ایلام", label: "ایلام" },
    { value: "ایوان", label: "ایوان" },
    { value: "دهلران", label: "دهلران" },
    { value: "مهران", label: "مهران" },
    { value: "آبدانان", label: "آبدانان" },
    { value: "دره‌شهر", label: "دره‌شهر" },
    { value: "ملکشاهی", label: "ملکشاهی" },
    { value: "چرداول", label: "چرداول" },
    { value: "بدره", label: "بدره" },
  ],
  فارس: [
    { value: "شیراز", label: "شیراز" },
    { value: "مرودشت", label: "مرودشت" },
    { value: "کازرون", label: "کازرون" },
    { value: "جهرم", label: "جهرم" },
    { value: "لارستان", label: "لارستان" },
    { value: "فسا", label: "فسا" },
    { value: "داراب", label: "داراب" },
    { value: "سپیدان", label: "سپیدان" },
    { value: "لامرد", label: "لامرد" },
    { value: "فیروزآباد", label: "فیروزآباد" },
    { value: "نی‌ریز", label: "نی‌ریز" },
    { value: "استهبان", label: "استهبان" },
    { value: "زرین‌دشت", label: "زرین‌دشت" },
    { value: "اقلید", label: "اقلید" },
    { value: "آباده", label: "آباده" },
    { value: "ممسنی", label: "ممسنی" },
    { value: "رستم", label: "رستم" },
    { value: "خرامه", label: "خرامه" },
    { value: "خنج", label: "خنج" },
    { value: "سروستان", label: "سروستان" },
    { value: "کوار", label: "کوار" },
    { value: "قیر و کارزین", label: "قیر و کارزین" },
    { value: "پاسارگاد", label: "پاسارگاد" },
    { value: "بوانات", label: "بوانات" },
    { value: "بیضا", label: "بیضا" },
  ],
  بوشهر: [
    { value: "بوشهر", label: "بوشهر" },
    { value: "دشتی", label: "دشتی" },
    { value: "دشتستان", label: "دشتستان" },
    { value: "تنگستان", label: "تنگستان" },
    { value: "کنگان", label: "کنگان" },
    { value: "جم", label: "جم" },
    { value: "گناوه", label: "گناوه" },
    { value: "دیر", label: "دیر" },
    { value: "عسلویه", label: "عسلویه" },
    { value: "دیلم", label: "دیلم" },
  ],
  زنجان: [
    { value: "زنجان", label: "زنجان" },
    { value: "ابهر", label: "ابهر" },
    { value: "خرمدره", label: "خرمدره" },
    { value: "خدابنده", label: "خدابنده" },
    { value: "ایجرود", label: "ایجرود" },
    { value: "ماهنشان", label: "ماهنشان" },
    { value: "سلطانیه", label: "سلطانیه" },
    { value: "طارم", label: "طارم" },
  ],
  "آذربایجان شرقی": [
    { value: "تبریز", label: "تبریز" },
    { value: "مراغه", label: "مراغه" },
    { value: "مرند", label: "مرند" },
    { value: "اهر", label: "اهر" },
    { value: "شبستر", label: "شبستر" },
    { value: "سراب", label: "سراب" },
    { value: "میانه", label: "میانه" },
    { value: "هریس", label: "هریس" },
    { value: "آذرشهر", label: "آذرشهر" },
    { value: "بستان‌آباد", label: "بستان‌آباد" },
    { value: "اسکو", label: "اسکو" },
    { value: "بناب", label: "بناب" },
    { value: "هشترود", label: "هشترود" },
    { value: "چاراویماق", label: "چاراویماق" },
    { value: "جلفا", label: "جلفا" },
    { value: "کلیبر", label: "کلیبر" },
    { value: "ورزقان", label: "ورزقان" },
    { value: "ملکان", label: "ملکان" },
    { value: "خداآفرین", label: "خداآفرین" },
  ],
  "آذربایجان غربی": [
    { value: "ارومیه", label: "ارومیه" },
    { value: "خوی", label: "خوی" },
    { value: "میاندوآب", label: "میاندوآب" },
    { value: "بوکان", label: "بوکان" },
    { value: "سلماس", label: "سلماس" },
    { value: "نقده", label: "نقده" },
    { value: "مهاباد", label: "مهاباد" },
    { value: "پیرانشهر", label: "پیرانشهر" },
    { value: "ماکو", label: "ماکو" },
    { value: "سردشت", label: "سردشت" },
    { value: "تکاب", label: "تکاب" },
    { value: "شاهین‌دژ", label: "شاهین‌دژ" },
    { value: "چالدران", label: "چالدران" },
    { value: "اشنویه", label: "اشنویه" },
    { value: "چایپاره", label: "چایپاره" },
    { value: "پلدشت", label: "پلدشت" },
    { value: "شوط", label: "شوط" },
  ],
  "خراسان رضوی": [
    { value: "مشهد", label: "مشهد" },
    { value: "نیشابور", label: "نیشابور" },
    { value: "سبزوار", label: "سبزوار" },
    { value: "تربت‌حیدریه", label: "تربت‌حیدریه" },
    { value: "قوچان", label: "قوچان" },
    { value: "کاشمر", label: "کاشمر" },
    { value: "تربت‌جام", label: "تربت‌جام" },
    { value: "خواف", label: "خواف" },
    { value: "چناران", label: "چناران" },
    { value: "درگز", label: "درگز" },
    { value: "سرخس", label: "سرخس" },
    { value: "گناباد", label: "گناباد" },
    { value: "بردسکن", label: "بردسکن" },
    { value: "فریمان", label: "فریمان" },
    { value: "طرقبه و شاندیز", label: "طرقبه و شاندیز" },
    { value: "باخرز", label: "باخرز" },
    { value: "رشتخوار", label: "رشتخوار" },
    { value: "فیروزه", label: "فیروزه" },
    { value: "بینالود", label: "بینالود" },
    { value: "جغتای", label: "جغتای" },
    { value: "جوین", label: "جوین" },
    { value: "زاوه", label: "زاوه" },
    { value: "کلات", label: "کلات" },
    { value: "صالح‌آباد", label: "صالح‌آباد" },
  ],
  البرز: [
    { value: "کرج", label: "کرج" },
    { value: "ساوجبلاغ", label: "ساوجبلاغ" },
    { value: "نظرآباد", label: "نظرآباد" },
    { value: "طالقان", label: "طالقان" },
    { value: "اشتهارد", label: "اشتهارد" },
    { value: "فردیس", label: "فردیس" },
  ],
  سمنان: [
    { value: "سمنان", label: "سمنان" },
    { value: "شاهرود", label: "شاهرود" },
    { value: "دامغان", label: "دامغان" },
    { value: "گرمسار", label: "گرمسار" },
    { value: "مهدی‌شهر", label: "مهدی‌شهر" },
    { value: "آرادان", label: "آرادان" },
    { value: "میامی", label: "میامی" },
    { value: "سرخه", label: "سرخه" },
  ],
  قزوین: [
    { value: "قزوین", label: "قزوین" },
    { value: "البرز", label: "البرز" },
    { value: "آبیک", label: "آبیک" },
    { value: "تاکستان", label: "تاکستان" },
    { value: "بوئین‌زهرا", label: "بوئین‌زهرا" },
    { value: "آوج", label: "آوج" },
  ],
  قم: [{ value: "قم", label: "قم" }],
  "سیستان و بلوچستان": [
    { value: "زاهدان", label: "زاهدان" },
    { value: "زابل", label: "زابل" },
    { value: "خاش", label: "خاش" },
    { value: "سراوان", label: "سراوان" },
    { value: "ایرانشهر", label: "ایرانشهر" },
    { value: "چابهار", label: "چابهار" },
    { value: "نیک‌شهر", label: "نیک‌شهر" },
    { value: "سرباز", label: "سرباز" },
    { value: "کنارک", label: "کنارک" },
    { value: "میرجاوه", label: "میرجاوه" },
    { value: "هیرمند", label: "هیرمند" },
    { value: "زهک", label: "زهک" },
    { value: "سیب و سوران", label: "سیب و سوران" },
    { value: "فنوج", label: "فنوج" },
    { value: "قصرقند", label: "قصرقند" },
    { value: "دلگان", label: "دلگان" },
    { value: "بمپور", label: "بمپور" },
    { value: "نیمروز", label: "نیمروز" },
    { value: "مهرستان", label: "مهرستان" },
    { value: "هامون", label: "هامون" },
    { value: "تفتان", label: "تفتان" },
    { value: "راسک", label: "راسک" },
    { value: "بزمان", label: "بزمان" },
    { value: "سوران", label: "سوران" },
    { value: "بنجار", label: "بنجار" },
    { value: "محمدان", label: "محمدان" },
  ],
  کردستان: [
    { value: "سنندج", label: "سنندج" },
    { value: "سقز", label: "سقز" },
    { value: "بانه", label: "بانه" },
    { value: "مریوان", label: "مریوان" },
    { value: "بیجار", label: "بیجار" },
    { value: "قروه", label: "قروه" },
    { value: "کامیاران", label: "کامیاران" },
    { value: "دیواندره", label: "دیواندره" },
    { value: "دهگلان", label: "دهگلان" },
    { value: "سروآباد", label: "سروآباد" },
  ],
  کرمان: [
    { value: "کرمان", label: "کرمان" },
    { value: "سیرجان", label: "سیرجان" },
    { value: "رفسنجان", label: "رفسنجان" },
    { value: "جیرفت", label: "جیرفت" },
    { value: "بم", label: "بم" },
    { value: "زرند", label: "زرند" },
    { value: "شهربابک", label: "شهربابک" },
    { value: "کهنوج", label: "کهنوج" },
    { value: "بافت", label: "بافت" },
    { value: "عنبرآباد", label: "عنبرآباد" },
    { value: "بردسیر", label: "بردسیر" },
    { value: "ریگان", label: "ریگان" },
    { value: "فهرج", label: "فهرج" },
    { value: "نرماشیر", label: "نرماشیر" },
    { value: "راور", label: "راور" },
    { value: "رودبار جنوب", label: "رودبار جنوب" },
    { value: "منوجان", label: "منوجان" },
    { value: "قلعه گنج", label: "قلعه گنج" },
    { value: "ارزوئیه", label: "ارزوئیه" },
    { value: "فاریاب", label: "فاریاب" },
    { value: "رابر", label: "رابر" },
    { value: "انار", label: "انار" },
  ],
  کرمانشاه: [
    { value: "کرمانشاه", label: "کرمانشاه" },
    { value: "اسلام‌آباد غرب", label: "اسلام‌آباد غرب" },
    { value: "سرپل ذهاب", label: "سرپل ذهاب" },
    { value: "جوانرود", label: "جوانرود" },
    { value: "پاوه", label: "پاوه" },
    { value: "سنقر", label: "سنقر" },
    { value: "کنگاور", label: "کنگاور" },
    { value: "صحنه", label: "صحنه" },
    { value: "هرسین", label: "هرسین" },
    { value: "گیلانغرب", label: "گیلانغرب" },
    { value: "روانسر", label: "روانسر" },
    { value: "قصر شیرین", label: "قصر شیرین" },
    { value: "دالاهو", label: "دالاهو" },
    { value: "ثلاث باباجانی", label: "ثلاث باباجانی" },
  ],
  "کهگیلویه و بویراحمد": [
    { value: "یاسوج", label: "یاسوج" },
    { value: "گچساران", label: "گچساران" },
    { value: "دهدشت", label: "دهدشت" },
    { value: "باشت", label: "باشت" },
    { value: "لیکک", label: "لیکک" },
    { value: "چرام", label: "چرام" },
    { value: "لنده", label: "لنده" },
    { value: "مارگون", label: "مارگون" },
    { value: "دنا", label: "دنا" },
  ],
  گلستان: [
    { value: "گرگان", label: "گرگان" },
    { value: "گنبد کاووس", label: "گنبد کاووس" },
    { value: "بندر ترکمن", label: "بندر ترکمن" },
    { value: "علی‌آباد کتول", label: "علی‌آباد کتول" },
    { value: "آزادشهر", label: "آزادشهر" },
    { value: "کردکوی", label: "کردکوی" },
    { value: "کلاله", label: "کلاله" },
    { value: "آق‌قلا", label: "آق‌قلا" },
    { value: "مینودشت", label: "مینودشت" },
    { value: "گالیکش", label: "گالیکش" },
    { value: "بندر گز", label: "بندر گز" },
    { value: "رامیان", label: "رامیان" },
    { value: "مراوه‌تپه", label: "مراوه‌تپه" },
    { value: "گمیشان", label: "گمیشان" },
  ],
  گیلان: [
    { value: "رشت", label: "رشت" },
    { value: "تالش", label: "تالش" },
    { value: "لاهیجان", label: "لاهیجان" },
    { value: "رودسر", label: "رودسر" },
    { value: "لنگرود", label: "لنگرود" },
    { value: "آستانه اشرفیه", label: "آستانه اشرفیه" },
    { value: "فومن", label: "فومن" },
    { value: "صومعه‌سرا", label: "صومعه‌سرا" },
    { value: "رضوانشهر", label: "رضوانشهر" },
    { value: "ماسال", label: "ماسال" },
    { value: "رودبار", label: "رودبار" },
    { value: "شفت", label: "شفت" },
    { value: "املش", label: "املش" },
    { value: "سیاهکل", label: "سیاهکل" },
    { value: "بندر انزلی", label: "بندر انزلی" },
  ],
  لرستان: [
    { value: "خرم‌آباد", label: "خرم‌آباد" },
    { value: "بروجرد", label: "بروجرد" },
    { value: "دورود", label: "دورود" },
    { value: "الیگودرز", label: "الیگودرز" },
    { value: "ازنا", label: "ازنا" },
    { value: "کوهدشت", label: "کوهدشت" },
    { value: "پلدختر", label: "پلدختر" },
    { value: "دلفان", label: "دلفان" },
    { value: "سلسله", label: "سلسله" },
    { value: "دوره", label: "دوره" },
    { value: "رومشکان", label: "رومشکان" },
  ],
  مازندران: [
    { value: "ساری", label: "ساری" },
    { value: "آمل", label: "آمل" },
    { value: "بابل", label: "بابل" },
    { value: "بابلسر", label: "بابلسر" },
    { value: "بهشهر", label: "بهشهر" },
    { value: "تنکابن", label: "تنکابن" },
    { value: "جویبار", label: "جویبار" },
    { value: "چالوس", label: "چالوس" },
    { value: "رامسر", label: "رامسر" },
    { value: "سوادکوه", label: "سوادکوه" },
    { value: "قائم‌شهر", label: "قائم‌شهر" },
    { value: "نکا", label: "نکا" },
    { value: "نوشهر", label: "نوشهر" },
    { value: "فریدون‌کنار", label: "فریدون‌کنار" },
    { value: "گلوگاه", label: "گلوگاه" },
    { value: "محمودآباد", label: "محمودآباد" },
    { value: "نور", label: "نور" },
    { value: "عباس‌آباد", label: "عباس‌آباد" },
    { value: "سوادکوه شمالی", label: "سوادکوه شمالی" },
    { value: "میان‌دورود", label: "میان‌دورود" },
  ],
  اردبیل: [
    { value: "اردبیل", label: "اردبیل" },
    { value: "مشگین‌شهر", label: "مشگین‌شهر" },
    { value: "پارس‌آباد", label: "پارس‌آباد" },
    { value: "خلخال", label: "خلخال" },
    { value: "نمین", label: "نمین" },
    { value: "گرمی", label: "گرمی" },
    { value: "بیله‌سوار", label: "بیله‌سوار" },
    { value: "اصلاندوز", label: "اصلاندوز" },
    { value: "نیر", label: "نیر" },
    { value: "کوثر", label: "کوثر" },
    { value: "انگوت", label: "انگوت" },
    { value: "سرعین", label: "سرعین" },
  ],
  "چهارمحال و بختیاری": [
    { value: "شهرکرد", label: "شهرکرد" },
    { value: "بروجن", label: "بروجن" },
    { value: "لردگان", label: "لردگان" },
    { value: "فارسان", label: "فارسان" },
    { value: "اردل", label: "اردل" },
    { value: "کیار", label: "کیار" },
    { value: "سامان", label: "سامان" },
    { value: "بن", label: "بن" },
    { value: "کوهرنگ", label: "کوهرنگ" },
  ],
  "خراسان جنوبی": [
    { value: "بیرجند", label: "بیرجند" },
    { value: "قائنات", label: "قائنات" },
    { value: "طبس", label: "طبس" },
    { value: "فردوس", label: "فردوس" },
    { value: "نهبندان", label: "نهبندان" },
    { value: "سرایان", label: "سرایان" },
    { value: "سربیشه", label: "سربیشه" },
    { value: "درمیان", label: "درمیان" },
    { value: "بشرویه", label: "بشرویه" },
    { value: "خوسف", label: "خوسف" },
    { value: "زیرکوه", label: "زیرکوه" },
  ],
  "خراسان شمالی": [
    { value: "بجنورد", label: "بجنورد" },
    { value: "شیروان", label: "شیروان" },
    { value: "اسفراین", label: "اسفراین" },
    { value: "مانه و سملقان", label: "مانه و سملقان" },
    { value: "جاجرم", label: "جاجرم" },
    { value: "فاروج", label: "فاروج" },
    { value: "گرمه", label: "گرمه" },
    { value: "راز و جرگلان", label: "راز و جرگلان" },
  ],
  خوزستان: [
    { value: "اهواز", label: "اهواز" },
    { value: "آبادان", label: "آبادان" },
    { value: "اندیمشک", label: "اندیمشک" },
    { value: "ایذه", label: "ایذه" },
    { value: "باغ‌ملک", label: "باغ‌ملک" },
    { value: "بندر ماهشهر", label: "بندر ماهشهر" },
    { value: "بهبهان", label: "بهبهان" },
    { value: "خرمشهر", label: "خرمشهر" },
    { value: "دزفول", label: "دزفول" },
    { value: "دشت آزادگان", label: "دشت آزادگان" },
    { value: "رامشیر", label: "رامشیر" },
    { value: "رامهرمز", label: "رامهرمز" },
    { value: "شادگان", label: "شادگان" },
    { value: "شوش", label: "شوش" },
    { value: "شوشتر", label: "شوشتر" },
    { value: "مسجدسلیمان", label: "مسجدسلیمان" },
    { value: "هویزه", label: "هویزه" },
    { value: "امیدیه", label: "امیدیه" },
    { value: "اندیکا", label: "اندیکا" },
    { value: "آغاجاری", label: "آغاجاری" },
    { value: "باوی", label: "باوی" },
    { value: "حمیدیه", label: "حمیدیه" },
    { value: "کارون", label: "کارون" },
    { value: "لالی", label: "لالی" },
    { value: "هفتکل", label: "هفتکل" },
  ],
  هرمزگان: [
    { value: "بندرعباس", label: "بندرعباس" },
    { value: "بندر لنگه", label: "بندر لنگه" },
    { value: "قشم", label: "قشم" },
    { value: "بستک", label: "بستک" },
    { value: "جاسک", label: "جاسک" },
    { value: "میناب", label: "میناب" },
    { value: "حاجی‌آباد", label: "حاجی‌آباد" },
    { value: "رودان", label: "رودان" },
    { value: "ابوموسی", label: "ابوموسی" },
    { value: "پارسیان", label: "پارسیان" },
    { value: "خمیر", label: "خمیر" },
    { value: "سیریک", label: "سیریک" },
    { value: "بشاگرد", label: "بشاگرد" },
  ],
  همدان: [
    { value: "همدان", label: "همدان" },
    { value: "ملایر", label: "ملایر" },
    { value: "نهاوند", label: "نهاوند" },
    { value: "کبودرآهنگ", label: "کبودرآهنگ" },
    { value: "تویسرکان", label: "تویسرکان" },
    { value: "رزن", label: "رزن" },
    { value: "اسدآباد", label: "اسدآباد" },
    { value: "فامنین", label: "فامنین" },
  ],
  یزد: [
    { value: "یزد", label: "یزد" },
    { value: "تفت", label: "تفت" },
    { value: "مهریز", label: "مهریز" },
    { value: "میبد", label: "میبد" },
    { value: "اردکان", label: "اردکان" },
    { value: "ابرکوه", label: "ابرکوه" },
    { value: "بافق", label: "بافق" },
    { value: "خاتم", label: "خاتم" },
    { value: "اشکذر", label: "اشکذر" },
    { value: "مهريز", label: "مهريز" },
  ],
};

// گزینه‌های مقطع تحصیلی
export const degreeOptions = [
  { value: "دیپلم", label: "دیپلم" },
  { value: "کاردانی", label: "کاردانی" },
  { value: "کارشناسی", label: "کارشناسی" },
  { value: "کارشناسی ارشد", label: "کارشناسی ارشد" },
  { value: "دکتری", label: "دکتری" },
  { value: "دکترای تخصصی", label: "دکترای تخصصی" },
];

// گزینه‌های رشته تحصیلی
export const fieldOptions = [
  { value: "حسابداری", label: "حسابداری" },
  { value: "مهندسی کامپیوتر", label: "مهندسی کامپیوتر" },
  { value: "مهندسی برق", label: "مهندسی برق" },
  { value: "علوم داده", label: "علوم داده" },
  { value: "مدیریت", label: "مدیریت" },
  { value: "مهندسی صنایع", label: "مهندسی صنایع" },
  { value: "مهندسی فناوری اطلاعات", label: "مهندسی فناوری اطلاعات" },
  { value: "علوم کامپیوتر", label: "علوم کامپیوتر" },
  { value: "اقتصاد", label: "اقتصاد" },
  { value: "MBA", label: "MBA" },
  { value: "آمار", label: "آمار" },
  { value: "روانشناسی عمومی", label: "روانشناسی عمومی" },
  { value: "روانشناسی تربیتی", label: "روانشناسی تربیتی" },
  {
    value: "علوم تربیتی(پیش دبستانی و دبستانی)",
    label: "علوم تربیتی(پیش دبستانی و دبستانی)",
  },
  { value: "روانشناسی کودکان استثنایی", label: "روانشناسی کودکان استثنایی" },
  {
    value: "رشد و پرورش کودکان پیشدبستانی(کودکان با نیازهای ویژه)",
    label: "رشد و پرورش کودکان پیشدبستانی(کودکان با نیازهای ویژه)",
  },
  {
    value: "تربیت مربی مراکز پیش از دبستان",
    label: "تربیت مربی مراکز پیش از دبستان",
  },
  { value: "مهندسی ریاضیات گسسته", label: "مهندسی ریاضیات گسسته" },
  { value: "ریاضیات محض", label: "ریاضیات محض" },
  { value: "ریاضی فیزیک", label: "ریاضی فیزیک" },
  { value: "آمار و احتمالات", label: "آمار و احتمالات" },
  { value: "مربی مهدکودک", label: "مربی مهدکودک" },
  { value: "کودکیاری", label: "کودکیاری" },
  { value: "مربی مهدکودک", label: "مربی مهدکودک" },
  { value: "تربیت مربی", label: "تربیت مربی" },
  {
    value: "مربی بهداشت مدارس و کودکیاری",
    label: "مربی بهداشت مدارس و کودکیاری",
  },
  { value: "مدیریت خانواده", label: "مدیریت خانواده" },
  { value: "مطالعات خانواده", label: "مطالعات خانواده" },
  { value: "مهندسی تکنولوژی نرم افزار", label: "مهندسی تکنولوژی نرم افزار" },
];

// مقادیر پیش‌فرض برای فرم
// export const defaultFormData = {
//   requestId: null,
//   requestCode: "",
//   requestDate: "",
//   requestRegisterDate: "",
//   requestHireTypeRef: "",
//   requestExecutiveBodyRef: "",
//   requestSubExecutiveBodyRef: "",
//   requestConfirmDate: "",
//   requestModel: "",
//   requestAuthDesc: "",
//   requestHireCapacity: "",
//   requestExtraCapacity: "",
//   requestJobCount: 0,
//   requestStatusRef: 1,
//   quotaTable: [], // اطمینان از اینکه quotaTable همیشه یک آرایه است
//   educationTable: [],
//   supplementaryEvaluationTable: [],
//   writtenExamTable: [],
//   practicalExamTable: [],
//   interviewExamTable: [],
//   generalExamTable: [], // اضافه کردن برای Step4
//   specializedExamTable: [], // اضافه کردن برای Step4
//   permitNumber: "",
//   rejectionReason: "",
// };


export const defaultFormData = {
  requestId: null,
  requestCode: "",
  requestDate: "",
  requestRegisterDate: "",
  requestHireTypeRef: "",
  requestExecutiveBodyRef: "",
  requestSubExecutiveBodyRef: "",
  requestConfirmDate: "",
  requestModel: "",
  requestAuthDesc: "",
  requestHireCapacity: "",
  requestExtraCapacity: "",
  requestJobCount: 0,
  requestStatusRef: 1,
  employmentType: "", // اضافه شده
  scoreRatio: "", // اضافه شده
  capacityMultiplier: "", // اضافه شده
  specialConditions: "", // اضافه شده
  quotaTable: [],
  educationTable: [],
  supplementaryEvaluationTable: [],
  writtenExamTable: [],
  practicalExamTable: [],
  interviewExamTable: [],
  generalExamTable: [],
  specializedExamTable: [],
  permitNumber: "",
  permitExpirationDate: "", // اضافه شده
  permitImage: null, // اضافه شده
  description: "", // اضافه شده
  rejectionReason: "",
};